Repository wazuh/wazuh, pull requests merged in 2018-07, with the labels that each got.

#855 Fix variables parser when loading rules
  CHANGELOG.md
  src/os_xml/os_xml_variables.c
Labels: bug

#849 Add cluster's init.py to bump_version.sh
  contrib/bump_version.sh
Labels: framework

#874 Close all open files in the cluster
  CHANGELOG.md
  framework/wazuh/cluster/cluster.py
Labels: bug, cluster, framework

#870 Add exception when no agents are selected to restart
  CHANGELOG.md
  framework/wazuh/agent.py
  framework/wazuh/exception.py
Labels: framework

#810 Fix sort agents by status
  CHANGELOG.md
  framework/wazuh/agent.py
Labels: bug, framework

#872 Remove old snapshot files for FIM
  etc/templates/config/generic/syscheck.agent.template
  etc/templates/config/generic/syscheck.manager.template
  src/config/syscheck-config.c
  src/config/syscheck-config.h
  src/headers/syscheck_op.h
  src/shared/syscheck_op.c
  src/syscheckd/config.c
  src/syscheckd/create_db.c
  src/syscheckd/run_check.c
  src/win32/ossec.conf
Labels: fim

#800 Prevent cluster from exiting when a socket error is raised at start
  CHANGELOG.md
  framework/scripts/wazuh-clusterd.py
  framework/wazuh/cluster/client.py
  framework/wazuh/cluster/communication.py
Labels: framework

#887 Fixed empty rule file checking
  src/analysisd/decoders/decode-xml.c
  src/analysisd/rules.c
  src/headers/file_op.h
  src/shared/file_op.c
  src/shared/rules_op.c
Labels: bug

#850 Rename cluster clients to workers
  CHANGELOG.md
  framework/scripts/cluster_control.py
  framework/scripts/wazuh-clusterd.py
  framework/tests/test_cluster_sync.py
  framework/tests/test_communication.py
  framework/wazuh/cluster/cluster.json
  framework/wazuh/cluster/cluster.py
  framework/wazuh/cluster/communication.py
  framework/wazuh/cluster/control.py
  framework/wazuh/cluster/master.py
  framework/wazuh/cluster/worker.py
  framework/wazuh/exception.py
  src/external/audit-userspace/auparse/test/auparse_test.py
  src/external/audit-userspace/autogen.sh
  src/external/audit-userspace/compile
  src/external/audit-userspace/config.guess
  src/external/audit-userspace/config.sub
  src/external/audit-userspace/configure
  src/external/audit-userspace/contrib/avc_snap
  src/external/audit-userspace/depcomp
  src/external/audit-userspace/install-sh
  src/external/audit-userspace/missing
  src/external/audit-userspace/py-compile
  src/external/audit-userspace/test-driver
Labels: cluster, framework

#891 Limit maximum number of items returned by API
  framework/examples/rules2csv.py
  framework/scripts/agent_groups.py
  framework/wazuh/agent.py
  framework/wazuh/common.py
  framework/wazuh/configuration.py
  framework/wazuh/decoder.py
  framework/wazuh/exception.py
  framework/wazuh/rootcheck.py
  framework/wazuh/rule.py
  framework/wazuh/syscheck.py
  framework/wazuh/syscollector.py
  framework/wazuh/utils.py
Labels: API, framework

#920 Add support for GET/agents/stats/distinct API request
  CHANGELOG.md
  framework/wazuh/distinct.py
Labels: API, enhancement, framework

#865 Add support for unified WPK
  CHANGELOG.md
  framework/scripts/agent_upgrade.py
  framework/wazuh/agent.py
  framework/wazuh/exception.py
  src/os_execd/wcom.c
Labels: enhancement, wpk

#663 Improve framework's configuration parser when there are repeated sections
  framework/wazuh/configuration.py
Labels: bug, framework

#667 Cluster log rotation: set correct permissions and store rotations in /logs/ossec
  framework/scripts/wazuh-clusterd.py
  framework/wazuh/cluster/cluster.py
  src/init/inst-functions.sh
Labels: enhancement, framework

#761 Rename merge sum and config sum in GET/agents/groups
  framework/wazuh/agent.py
Labels: framework

#892 Reject connection if client has a different cluster name
  active-response/firewalls/default-firewall-drop.sh
  framework/wazuh/cluster/communication.py
  framework/wazuh/cluster/worker.py
  src/init/wazuh/wazuh.sh
Labels: cluster, framework

#916 Add flag to disable the audit built for incompatible systems
  install.sh
  src/Makefile
  src/syscheckd/syscheck.c
  src/syscheckd/syscheck_audit.c
  src/wazuh_modules/wm_ciscat.h
Labels: bug, fim

#814 Ignore uppercase and lowercase sorting an array
  CHANGELOG.md
  framework/wazuh/utils.py
Labels: bug, framework

#856 Fix bugs reading logs in framework
  CHANGELOG.md
  framework/wazuh/manager.py
  framework/wazuh/utils.py
Labels: bug, framework

#934 Return nested data in syscollector API calls for multiple agents
  framework/wazuh/syscollector.py
Labels: API, framework

#944 Fix inconsistent status of the Wazuh service in CentOS 6
  src/init/ossec-server.sh
Labels: bug, cluster

#942 Fix "Could not connect to wdb socket: No such file or directory" error
  CHANGELOG.md
  framework/wazuh/wdb.py
Labels: API, bug, framework

#798 Add option to download the wpk using http
  CHANGELOG.md
  active-response/firewalls/default-firewall-drop.sh
  framework/scripts/agent_upgrade.py
  framework/wazuh/agent.py
  framework/wazuh/common.py
  src/init/wazuh/wazuh.sh
Labels: enhancement, framework

#949 Fix "TypeError: '>' not supported between instances of 'str' and 'int'" error in cluster_control
  framework/wazuh/cluster/master.py
Labels: bug, cluster, framework

#960 Fix wrong file paths in Audit events
  src/syscheckd/run_realtime.c
  src/syscheckd/syscheck_audit.c
Labels: bug, fim

#958 Fix Remoted connection failed warning in TCP mode due to timeout
  CHANGELOG.md
  src/remoted/remoted.c
  src/remoted/syslogtcp.c
Labels: bug

#959 Fix call to sleep function inside a locked section
  src/syscheckd/create_db.c
  src/syscheckd/syscheck.c
Labels: bug, fim

#966 Fix memory leak in Syscheck
  src/syscheckd/create_db.c
Labels: bug, fim

#967 Fix error control in Virustotal integration
  integrations/virustotal
Labels: bug

#968 Ignore some Windows Audit events by the default configuration
  src/win32/ossec.conf
Labels: fim

#969 Filter invalid auid values
  src/syscheckd/syscheck_audit.c
Labels: fim

#973 Fix option USE_AUDIT for OS without audit
  install.sh
Labels: fim

#983 Fix monitord segfault when rotating logs
  src/monitord/sign_log.c
Labels: bug

#990 Fix agent compilation on Solaris
  src/Makefile
Labels: bug

#1002 Improve cluster_control to show an error if the status does not exist
  CHANGELOG.md
  framework/scripts/cluster_control.py
Labels: cluster, enhancement

#1012 Avoid null pointer access in network scan
  src/wazuh_modules/syscollector/syscollector_linux.c
Labels: bug

#1023 Fix centos5 default configuration file
  src/init/dist-detect.sh
  src/init/inst-functions.sh
Labels: bug

#1025 New fields to Syscollector API calls
  framework/wazuh/syscollector.py
Labels: API, enhancement, framework

#1032 Hide the ossec user in MacOS X
  src/init/osx105-addusers.sh
Labels: bug
