Repository wazuh/wazuh, pull requests merged in 2018-09, with the labels that each got.

#1052 Fix id format in json output log.
  src/analysisd/format/to_json.c
Labels: bug

#1220 Fix bug when migrating AWS database
  wodles/aws/aws-s3.py
Labels: bug

#1225 Fix bug when checking agent configuration in logcollector
  CHANGELOG.md
  src/config/localfile-config.c
Labels: bug

#1226 Equal recursion level for real-time and scheduled scans
  CHANGELOG.md
  src/syscheckd/run_realtime.c
Labels: bug, fim

#1229 Fix errors when parsing AWS events in elasticsearch
  wodles/aws/aws-s3.py
Labels: bug

#1230 Fix bug when launching osquery from Wazuh
  CHANGELOG.md
  src/shared/json_op.c
Labels: bug

#1231 Keep config files while upgrading Wazuh agent
  src/win32/wazuh-installer.wxs
Labels: bug

#921 Refactor DB queries in framework
  CHANGELOG.md
  active-response/kaspersky.py
  active-response/kaspersky.sh
  framework/wazuh/agent.py
  framework/wazuh/distinct.py
  framework/wazuh/exception.py
  framework/wazuh/rootcheck.py
  framework/wazuh/syscheck.py
  framework/wazuh/utils.py
  src/wazuh_db/schema_global.sql
  src/wazuh_db/wdb_agent.c
Labels: API, framework

#1285 Fix error in to_dict function.
  framework/wazuh/agent.py
Labels: bug, framework

#1286 Fix bug which only appears using Python 3 when agent data is loaded.
  framework/wazuh/agent.py
Labels: bug, framework

#1293 Fix bug that prevents the agent from restarting
  src/client-agent/restart_agent.c
Labels: bug

#1294 Fix error condition in restart_agent
  src/client-agent/restart_agent.c
Labels: bug

#1267 Fixing coverity errors
  src/analysisd/analysisd.c
  src/analysisd/rules.c
  src/client-agent/request.c
  src/headers/mq_op.h
  src/logcollector/main.c
  src/os_net/os_net.c
  src/os_regex/os_regex_execute.c
  src/remoted/request.c
  src/shared/file-queue.c
  src/shared/file_op.c
  src/shared/list_op.c
  src/shared/mq_op.c
  src/shared/vector_op.c
  src/syscheckd/seechanges.c
  src/wazuh_db/wdb_agent.c
  src/wazuh_modules/wmodules.c
Labels: bug

#1320 Fixed mem-leak
  src/wazuh_modules/syscollector/syscollector_linux.c
Labels: bug

#1242 Fix typo in whodata alerts
  CHANGELOG.md
  src/analysisd/format/to_json.c
Labels: bug, fim

#1296 Improve: Get agent configuration from API
  framework/wazuh/agent.py
  framework/wazuh/exception.py
  framework/wazuh/utils.py
  src/client-agent/request.c
  src/os_auth/config.c
  src/os_maild/config.c
  src/os_maild/mailcom.c
  src/os_maild/maild.c
  src/os_maild/maild.h
  src/remoted/config.c
  src/syscheckd/syscom.c
  src/wazuh_modules/wm_ciscat.c
Labels: bug, framework

#1233 Fix bug in whodata field extraction for Windows
  CHANGELOG.md
  src/analysisd/decoders/syscheck.c
  src/analysisd/format/to_json.c
  src/analysisd/format/to_json.h
  src/error_messages/error_messages.h
  src/syscheckd/create_db.c
  src/syscheckd/win_whodata.c
Labels: bug

#1332 Fix memory leak when getting the DHCP status
  src/wazuh_modules/syscollector/syscollector_linux.c
Labels: bug

#1306 Add Azure-logs module
  CHANGELOG.md
  etc/decoders/0485-azure_decoders.xml
  etc/rules/0015-ossec_rules.xml
  etc/rules/0580-azure_rules.xml
  src/config/wmodules-azure.c
  src/config/wmodules-config.c
  src/init/inst-functions.sh
  src/wazuh_modules/syscollector/syscollector_common.c
  src/wazuh_modules/wm_azure.c
  src/wazuh_modules/wm_azure.h
  src/wazuh_modules/wm_ciscat.c
  src/wazuh_modules/wm_ciscat.h
  src/wazuh_modules/wmodules.c
  src/wazuh_modules/wmodules.h
  wodles/azure/azure-logs.py
Labels: enhancement, needs ruleset

#1193 Fixed email_to array filling
  CHANGELOG.md
  src/config/email-alerts-config.c
Labels: bug

#1206 Fixing open-scap deadlock when opening large files
  CHANGELOG.md
  wodles/oscap/oscap.py
Labels: bug

#1346 Change error message to debug
  src/syscheckd/syscheck_audit.c
Labels: fim

#1336 Fix undefined client waiting in Authd
  CHANGELOG.md
  etc/internal_options.conf
  src/client-agent/start_agent.c
  src/config/authd-config.h
  src/os_auth/config.c
  src/os_auth/local-server.c
  src/os_auth/main-server.c
  src/os_maild/sendmail.c
  src/os_net/os_net.c
  src/os_net/os_net.h
  src/remoted/remoted.c
Labels: bug, needs documentation

#1347 Decoding error
  framework/wazuh/wdb.py
Labels: bug, framework

#1330 Set thread stack size as internal option for Unix systems
  etc/internal_options.conf
  src/headers/pthreads_op.h
  src/shared/pthreads_op.c
  src/wazuh_modules/main.c
Labels: bug

#1349 Make Syscheck case insensitive
  CHANGELOG.md
  src/config/syscheck-config.c
  src/headers/string_op.h
  src/syscheckd/create_db.c
  src/syscheckd/run_check.c
  src/syscheckd/run_realtime.c
Labels: enhancement, fim

#1352 Fix missing decoder info and dynamic fields in alerts
  src/analysisd/eventinfo.c
Labels: analysisd, bug

#1203 Fix getting ram inventory for Mac OS X and FreeBSD
  CHANGELOG.md
  src/wazuh_modules/syscollector/syscollector_bsd.c
Labels: bug

#1361 Fix the cleaning of the temporary folder
  CHANGELOG.md
  src/init/ossec-client.sh
  src/init/ossec-local.sh
  src/init/ossec-server.sh
Labels: bug

#1364 Fix check_mtime and check_inode view in Syscheck alert
  CHANGELOG.md
  src/analysisd/decoders/syscheck.c
Labels: bug, fim

#1333 Store FIM events in SQLite with Wazuh-db
  CHANGELOG.md
  src/analysisd/analysisd.c
  src/analysisd/analysisd.h
  src/analysisd/cleanevent.c
  src/analysisd/decoders/decoder.h
  src/analysisd/decoders/syscheck.c
  src/analysisd/lists_list.c
  src/headers/rc.h
  src/headers/syscheck_op.h
  src/shared/syscheck_op.c
  src/syscheckd/create_db.c
  src/syscheckd/run_check.c
  src/wazuh_db/main.c
  src/wazuh_db/schema_agents.sql
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_fim.c
  src/wazuh_db/wdb_metadata.c
  src/wazuh_db/wdb_parser.c
Labels: analysisd, enhancement, fim, needs documentation

#885 Distributed API
  framework/Makefile
  framework/scripts/cluster_control.py
  framework/scripts/wazuh-clusterd.py
  framework/wazuh/agent.py
  framework/wazuh/cluster/cluster.json
  framework/wazuh/cluster/cluster.py
  framework/wazuh/cluster/communication.py
  framework/wazuh/cluster/control.py
  framework/wazuh/cluster/dapi/__init__.py
  framework/wazuh/cluster/dapi/dapi.py
  framework/wazuh/cluster/dapi/requests_list.py
  framework/wazuh/cluster/internal_socket.py
  framework/wazuh/cluster/master.py
  framework/wazuh/cluster/worker.py
  framework/wazuh/common.py
  framework/wazuh/exception.py
  framework/wazuh/syscollector.py
  framework/wazuh/utils.py
  src/update/ruleset/update_ruleset
Labels: API, cluster, framework

#1365 Dev 37 query config continuation
  framework/wazuh/agent.py
  framework/wazuh/cluster/master.py
  framework/wazuh/exception.py
  src/agentlessd/lessdcom.c
  src/analysisd/config_json.c
  src/analysisd/rules.c
  src/analysisd/rules.h
  src/analysisd/syscom.c
  src/client-agent/agcom.c
  src/client-agent/request.c
  src/config/localfile-config.c
  src/headers/defs.h
  src/logcollector/lccom.c
  src/monitord/moncom.c
  src/os_auth/authcom.c
  src/os_csyslogd/csyscom.c
  src/os_csyslogd/main.c
  src/os_execd/config.c
  src/os_execd/execd.h
  src/os_execd/wcom.c
  src/os_integrator/intgcom.c
  src/os_integrator/main.c
  src/os_maild/config.c
  src/os_maild/mailcom.c
  src/os_net/os_net.c
  src/os_net/os_net.h
  src/syscheckd/syscom.c
  src/wazuh_modules/wmcom.c
Labels: enhancement

#1388 Add an option to disable distributed api
  framework/wazuh/cluster/cluster.json
  framework/wazuh/cluster/dapi/dapi.py
Labels: API, cluster, framework

#1381 Fixed /agents/outdated call. Now, this call returns only outdated age…
  framework/wazuh/agent.py
Labels: bug

#1379 Fix error in ossec-control that wasn't starting wazuh-clusterd
  src/init/ossec-server.sh
Labels: bug, cluster

#1358 Add hash parameter to GET/agents/groups/:group_id/files API call
  active-response/kaspersky.py
  active-response/kaspersky.sh
  framework/wazuh/agent.py
  framework/wazuh/exception.py
  framework/wazuh/utils.py
  src/update/ruleset/update_ruleset
Labels: API, framework

#1389 Error in recv function
  src/os_net/os_net.c
Labels: bug, testing

#1428 Fix compilation error for Windows
  src/os_execd/wcom.c
Labels: bug

#1432 Replace the send function between the Syscollector decoder and Wazuh-DB
  src/analysisd/decoders/syscollector.c
Labels: bug

#1383 Check the default-local_internal_options.conf file when upgrading by Windows MSI package
  src/win32/InstallerScripts.vbs
Labels: bug

#1437 Return agents groups as a list in agents API calls
  framework/wazuh/agent.py
  framework/wazuh/utils.py
Labels: API, framework

#1445 Fix directory checking in Syscheck for Windows
  src/shared/syscheck_op.c
Labels: bug, fim

#1447 Prevent cluster from blocking when its configuration is requested from the API
  framework/wazuh/cluster/dapi/dapi.py
  framework/wazuh/cluster/master.py
Labels: API, bug, cluster, framework

#1450 Add labels to manager configuration in JSON
  src/analysisd/config.c
  src/analysisd/config.h
  src/analysisd/syscom.c
Labels: analysisd, bug, v3.7.0

#1448 Fix clean sdbmemory
  src/analysisd/decoders/syscheck.c
  src/syscheckd/run_check.c
  src/wazuh_db/main.c
Labels: bug

#1454 Avoid error in Wazuh-DB at clean exit
  src/wazuh_db/main.c
Labels: bug

#1456 Output messages FIM configuration
  src/syscheckd/create_db.c
  src/syscheckd/syscheck.c
  src/syscheckd/win-registry.c
Labels: fim

#1460 Fix socket connection between authd and manage_agents
  src/addagent/manage_agents.c
  src/os_auth/local-server.c
Labels: bug

#1462 Improve error mesage in Analysisd when Wazuh DB is not running
  src/analysisd/decoders/syscheck.c
Labels: analysisd, fim

#1458 Read reports config in JSON
  src/monitord/moncom.c
  src/monitord/monitord.c
  src/monitord/monitord.h
Labels: bug, v3.7.0

#1465 Fix report_changes with a big ammount of files
  CHANGELOG.md
  src/shared/syscheck_op.c
  src/syscheckd/create_db.c
Labels: bug

#1466 Change -n option to -l in the Cluster test
  .github/ISSUE_TEMPLATE/test--cluster.md
Labels: bug

#1470 Prevent malfunction due to loss of FIM's control messages
  src/analysisd/decoders/syscheck.c
Labels: fim
