Repository wazuh/wazuh, pull requests merged in 2018-11, with the labels that each got.

#1793 Allow audispd to read af_wazuh.conf to fix whodata engine
  src/selinux/wazuh.te
Labels: bug, fim

#1782 Add PEM and KEY to the MSI package
  src/win32/wazuh-installer.wxs
Labels: agent, packages

#1788 Print all previous events in json format
  src/analysisd/format/to_json.c
Labels: bug

#1794 Fixed multigroup db length
  src/wazuh_modules/wm_database.c
Labels: bug

#1800 Fix inconsistencies when showing the firedtimes value
  src/analysisd/analysisd.c
  src/analysisd/eventinfo.c
  src/analysisd/eventinfo.h
  src/analysisd/format/to_json.c
Labels: analysisd, bug

#1802 Analysisd's decoders reconnect with Wazuh-DB
  src/analysisd/analysisd.h
  src/analysisd/decoders/syscheck.c
  src/analysisd/decoders/syscollector.c
Labels: enhancement

#1808 Fix error in the synchronization of nonexistent agents
  src/wazuh_modules/wm_database.c
Labels: bug, v3.7.0-pre

#1812 Add error description in socket operations
  src/agentlessd/lessdcom.c
  src/analysisd/analysisd.c
  src/analysisd/analysisd.h
  src/analysisd/asyscom.c
  src/logcollector/lccom.c
  src/monitord/moncom.c
  src/os_csyslogd/csyscom.c
  src/os_execd/wcom.c
  src/os_integrator/intgcom.c
  src/os_maild/mailcom.c
  src/syscheckd/syscom.c
  src/wazuh_modules/wmcom.c
Labels: enhancement, v3.7.0-pre

#1814 Added exception for mkdir
  framework/wazuh/utils.py
Labels: bug

#1816 3.7 fix Suse
  src/init/dist-detect.sh
Labels: suse

#1821 Fixes in unit tests
  src/Makefile
  src/os_regex/os_regex_free_pattern.c
  src/os_xml/os_xml.c
  src/tests/test_os_regex.c
  src/util/ossec-regex.c
Labels: bug, qa

#1830 Fix bug in UNIX socket library
  src/os_net/os_net.c
Labels: bug

#1834 Fix bug in Analysisd when reconnecting to the Wazuh DB
  src/analysisd/decoders/syscheck.c
  src/analysisd/decoders/syscollector.c
Labels: analysisd, bug

#1867 Discard invalid entries in syscheck database
  tools/migration/fim_migrate.py
Labels: bug, fim

#1835 AWS Config support
  etc/rules/0350-amazon_rules.xml
  src/config/wmodules-aws.c
  wodles/aws/aws-s3.py
Labels: enhancement, framework

#1762 Fix whodata in Linux
  src/config/syscheck-config.h
  src/syscheckd/config.c
  src/syscheckd/create_db.c
  src/syscheckd/run_check.c
  src/syscheckd/run_realtime.c
  src/syscheckd/syscheck.c
  src/syscheckd/syscheck.h
  src/syscheckd/syscheck_audit.c
  src/syscheckd/win_whodata.c
Labels: bug, fim

#1845 AWS Trusted Advisor support
  etc/rules/0350-amazon_rules.xml
Labels: enhancement, framework

#1880 max_queue_buffer parameter was removed
  wodles/aws/aws-s3.py
Labels: bug, framework

#1873 Fix bugs in cluster_control binary
  framework/scripts/cluster_control.py
  framework/wazuh/cluster/dapi/dapi.py
Labels: bug, cluster, framework

#1882 Audit key options
  CHANGELOG.md
  src/config/config.c
  src/config/config.h
  src/config/syscheck-config.c
  src/config/syscheck-config.h
  src/syscheckd/syscheck.h
  src/syscheckd/syscheck_audit.c
Labels: fim, needs documentation

#1856 Add SSL cert option
  .travis.yml
  CHANGELOG.md
  contrib/specs/agent/preloaded-vars.conf
  contrib/specs/local/preloaded-vars.conf
  contrib/specs/server/preloaded-vars.conf
  etc/preloaded-vars.conf
  gen_ossec.sh
  install.sh
  src/init/inst-functions.sh
Labels: enhancement

#1890 Dev 3.7 guess agent group
  CHANGELOG.md
  etc/internal_options.conf
  src/remoted/config.c
  src/remoted/manager.c
  src/remoted/remoted.h
  src/remoted/request.c
Labels: enhancement, remoted

#1906 Fix: Sleep before starting wodle during agent's first run (#1394)
  CHANGELOG.md
  src/headers/shared.h
  src/wazuh_modules/syscollector/syscollector_common.c
  src/wazuh_modules/wm_aws.c
  src/wazuh_modules/wm_azure.c
  src/wazuh_modules/wm_ciscat.c
  src/wazuh_modules/wm_command.c
  src/wazuh_modules/wm_oscap.c
Labels: bug

#1786 Ignore whitespaces while reading options from conf files
  src/shared/validate_op.c
Labels: bug, pending merge

#1847 Fix agent's control message truncation in Remoted
  CHANGELOG.md
  src/remoted/manager.c
Labels: bug

#1902 Fix and improve critical sections in Remoted
  CHANGELOG.md
  src/headers/hash_op.h
  src/headers/sec.h
  src/os_crypto/shared/keys.c
  src/remoted/manager.c
  src/remoted/remoted.h
  src/remoted/secure.c
  src/remoted/sendmsg.c
  src/shared/hash_op.c
  src/shared/mem_op.c
Labels: bug, remoted

#1923 Fix when reading Syscheck configuration
  src/config/syscheck-config.c
Labels: bug

#1931 Read restrict option
  src/syscheckd/config.c
Labels: bug

#1915 Remove option <remove_old-diff>
  etc/templates/config/darwin/syscheck.agent.template
  etc/templates/config/darwin/syscheck.manager.template
  etc/templates/config/generic/syscheck.agent.template
  etc/templates/config/generic/syscheck.manager.template
  src/config/syscheck-config.c
  src/config/syscheck-config.h
  src/syscheckd/config.c
  src/syscheckd/create_db.c
  src/win32/ossec.conf
Labels: fim

#1937 Fix bug in agent_groups binary when Wazuh is installed in a custom directory
  framework/scripts/agent_groups.py
Labels: bug, framework

#1929 Add some improvements and fixes in whodata
  CHANGELOG.md
  src/config/syscheck-config.c
  src/config/syscheck-config.h
  src/headers/vector_op.h
  src/init/ossec-client.sh
  src/init/ossec-local.sh
  src/init/ossec-server.sh
  src/shared/vector_op.c
  src/syscheckd/config.c
  src/syscheckd/create_db.c
  src/syscheckd/run_check.c
  src/syscheckd/run_realtime.c
  src/syscheckd/syscheck.c
  src/syscheckd/syscheck.h
  src/syscheckd/syscheck_audit.c
  src/syscheckd/win_whodata.c
Labels: enhancement, fim

#1934 Update agent_groups.py
  framework/scripts/agent_groups.py
Labels: needs documentation

#1936 Fix multiple bugs in cluster configuration
  framework/wazuh/cluster/cluster.py
  src/config/cluster-config.c
Labels: cluster, framework

#1866 Add tracing information to logs
  CHANGELOG.md
  src/headers/debug_op.h
  src/shared/debug_op.c
  src/shared/exec_op.c
  src/wazuh_modules/wm_download.c
  src/wazuh_modules/wm_osquery_monitor.c
Labels: enhancement

#1879 Fix race condition when decoding file permissions
  CHANGELOG.md
  src/analysisd/decoders/syscheck.c
  src/headers/read-agents.h
  src/shared/read-agents.c
Labels: analysisd, bug

#1932 Restore support for Amazon Linux in vulnerability-detector
  CHANGELOG.md
  etc/rules/0520-vulnerability-detector.xml
  src/analysisd/format/to_json.c
  src/config/wmodules-vuln-detector.c
  src/wazuh_modules/wm_vuln_detector.c
  src/wazuh_modules/wm_vuln_detector.h
Labels: bug, needs documentation, needs ruleset, vuln detector

#1899 Support for AWS Inspector (part 2)
  etc/rules/0350-amazon_rules.xml
  src/config/wmodules-aws.c
  src/wazuh_modules/wm_aws.c
  src/wazuh_modules/wm_aws.h
  wodles/aws/aws-s3.py
Labels: aws_integration, enhancement, framework

#1919 Rules for Amazon KMS
  etc/rules/0350-amazon_rules.xml
Labels: aws_integration, framework

#1918 Add options to detect changes attributes and file permissions for Windows
  CHANGELOG.md
  src/analysisd/alerts/log.c
  src/analysisd/decoders/syscheck.c
  src/analysisd/eventinfo.c
  src/analysisd/eventinfo.h
  src/analysisd/format/to_json.c
  src/config/syscheck-config.c
  src/config/syscheck-config.h
  src/headers/defs.h
  src/headers/mem_op.h
  src/headers/read-agents.h
  src/headers/syscheck_op.h
  src/shared/read-agents.c
  src/shared/syscheck_op.c
  src/syscheckd/create_db.c
  src/syscheckd/run_check.c
  src/syscheckd/run_realtime.c
  src/syscheckd/syscheck.h
  src/syscheckd/win-registry.c
  src/syscheckd/win_whodata.c
  src/wazuh_db/schema_agents.sql
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb_fim.c
  src/wazuh_db/wdb_parser.c
  src/wazuh_modules/syscollector/syscollector_windows.c
Labels: fim

#1944 Fix Windows compilation issue
  src/shared/read-agents.c
Labels: bug

#1973 Update Guard Duty rules
  etc/rules/0350-amazon_rules.xml
Labels: aws_integration, framework

#1982 Add a socket unix server/client to the new cluster protocol
  framework/scripts/wazuh-clusterd.py
  framework/wazuh/cluster/client.py
  framework/wazuh/cluster/cluster.py
  framework/wazuh/cluster/common.py
  framework/wazuh/cluster/local_client.py
  framework/wazuh/cluster/local_server.py
  framework/wazuh/cluster/server.py
Labels: cluster, framework

#1986 Silence warning error in Syscheck on repeated inodes
  src/syscheckd/create_db.c
Labels: fim

#1994 Fixing inode hash table consitency when deleting in realtime
  src/headers/syscheck_op.h
  src/shared/syscheck_op.c
  src/syscheckd/run_check.c
Labels: bug, fim

#2004 Fix agent group updating in database module
  src/wazuh_modules/wm_database.c
Labels: bug

#1996 Fix bugs starting cluster
  framework/wazuh/cluster/cluster.py
Labels: bug, cluster, framework

#1992 Fix for VPC Flow logs
  src/config/wmodules-aws.c
  src/wazuh_modules/wm_aws.c
  wodles/aws/aws-s3.py
Labels: aws_integration, framework

#2009 Remove Audit rules auto-reloading function
  src/syscheckd/syscheck_audit.c
Labels: fim

#1760 Get process inventory for Windows avoiding WMIC.
  CHANGELOG.md
  src/Makefile
  src/logcollector/logcollector.c
  src/shared/file_op.c
  src/wazuh_modules/syscollector/syscollector.h
  src/wazuh_modules/syscollector/syscollector_win_ext.c
  src/wazuh_modules/syscollector/syscollector_windows.c
Labels: enhancement, syscollector
