Repository wazuh/wazuh, pull requests merged in 2018-08, with the labels that each got.

#1035 Prevent Remoted from downloading shared files if option '-m' is enabled
  src/remoted/manager.c
Labels: bug, priority

#1043 Fix scan_id length for processes scan
  src/analysisd/decoders/syscollector.c
  src/wazuh_modules/syscollector/syscollector_bsd.c
  src/wazuh_modules/syscollector/syscollector_linux.c
Labels: bug

#1044 Fix bug in Syscheck when looking for removed files in scheduled scans
  src/syscheckd/create_db.c
Labels: bug, fim

#1045 Fix agent group format
  framework/wazuh/agent.py
Labels: bug

#1046 Fix comparing path with no_diff option
  src/syscheckd/seechanges.c
Labels: bug

#1051 Avoid DB_NOTFOUND warning when collecting rpm packages
  src/wazuh_modules/syscollector/syscollector_linux.c
Labels: bug

#1047 Fix error with older C compilers
  src/shared/version_op.c
Labels: bug

#1048 Prevent Authd from quitting if the agent selects an invalid IP
  src/os_auth/main-server.c
Labels: bug

#1053 Fix bug when sorting in syscollector API calls
  framework/wazuh/syscollector.py
Labels: API, bug, framework

#1054 Fix bug when installing framework package
  framework/setup.py
Labels: bug, framework

#1055 Revert avoiding DB_NOTFOUND warning
  src/wazuh_modules/syscollector/syscollector_linux.c
Labels: bug

#1056 Active response enhancements / Kaspersky integration
  active-response/kaspersky.py
  active-response/kaspersky.sh
  src/analysisd/alerts/exec.c
  src/config/active-response.c
  src/config/active-response.h
  src/error_messages/error_messages.h
  src/init/inst-functions.sh
  src/remoted/ar-forward.c
  src/shared/string_op.c
Labels: enhancement, needs documentation

#1058 Add CIS-CAT API requests
  framework/wazuh/ciscat.py
Labels: API, enhancement, framework

#1059 Fix _get_versions function when comparing input version
  framework/wazuh/agent.py
Labels: bug

#1060 Fix variable size
  src/remoted/manager.c
Labels: bug

#1061 Fix using the uninitialized hash table mutex on Windows systems
  src/shared/hash_op.c
Labels: bug

#1066 Fix version detection in Centos5
  src/init/dist-detect.sh
Labels: bug

#1063 Fix ossec.conf generation on new installations
  src/win32/wazuh-installer.wxs
Labels: bug

#1068 Fix auditd error codes filtering
  src/syscheckd/syscheck_audit.c
Labels: bug, fim

#1070 Revert fix dead code in vuln-detector
  src/wazuh_modules/wm_vuln_detector.c
Labels: bug

#1090 Add default values to agent upgrade tool help
  framework/scripts/agent_upgrade.py
Labels: enhancement

#1077 Fix compile warning message
  src/syscheckd/win_whodata.c
Labels: bug

#1095 Fix multiple warnings from the buffer
  src/client-agent/buffer.c
Labels: bug

#672 Logcollector parallelization
  CHANGELOG.md
  etc/internal_options.conf
  src/REVISION
  src/config/localfile-config.c
  src/config/localfile-config.h
  src/error_messages/error_messages.h
  src/headers/mq_op.h
  src/logcollector/config.c
  src/logcollector/logcollector.c
  src/logcollector/logcollector.h
  src/logcollector/main.c
  src/logcollector/read_audit.c
  src/logcollector/read_command.c
  src/logcollector/read_djb_multilog.c
  src/logcollector/read_fullcommand.c
  src/logcollector/read_json.c
  src/logcollector/read_mssql_log.c
  src/logcollector/read_multiline.c
  src/logcollector/read_mysql_log.c
  src/logcollector/read_nmapg.c
  src/logcollector/read_ossecalert.c
  src/logcollector/read_postgresql_log.c
  src/logcollector/read_snortfull.c
  src/logcollector/read_syslog.c
  src/shared/mq_op.c
  src/win32/win_agent.c
Labels: enhancement, needs documentation, priority

#1102 Fix bad file descriptor error when ignore_output is enabled
  CHANGELOG.md
  src/shared/exec_op.c
  src/wazuh_modules/wm_command.c
  src/wazuh_modules/wm_exec.c
  src/wazuh_modules/wmodules.c
Labels: bug

#1118 Fix unknown severity in Red Hat systems
  CHANGELOG.md
  src/error_messages/debug_messages.h
  src/error_messages/error_messages.h
  src/wazuh_modules/wm_vuln_detector.c
  src/wazuh_modules/wm_vuln_detector.h
Labels: bug

#1128 Fix repeated wodle modules
  CHANGELOG.md
  src/config/wmodules-aws.c
  src/config/wmodules-ciscat.c
  src/config/wmodules-command.c
  src/config/wmodules-oscap.c
  src/config/wmodules-osquery-monitor.c
  src/config/wmodules-vuln-detector.c
  src/config/wmodules_syscollector.c
  src/wazuh_modules/wm_command.c
  src/wazuh_modules/wm_database.c
  src/wazuh_modules/wm_download.c
  src/wazuh_modules/wmodules.c
  src/wazuh_modules/wmodules.h
Labels: bug

#1137 Fix memory leaks in vulnerability-detector
  src/wazuh_modules/wm_vuln_detector.c
Labels: bug

#1131 Add support for more AWS services
  CHANGELOG.md
  etc/rules/0350-amazon_rules.xml
  extensions/elasticsearch/wazuh-elastic6-template-alerts.json
  extensions/logstash/01-wazuh-local.conf
  src/config/wmodules-aws.c
  src/config/wmodules-config.c
  src/init/inst-functions.sh
  src/init/update.sh
  src/wazuh_modules/wm_aws.c
  src/wazuh_modules/wm_aws.h
  wodles/aws/aws-cloudtrail.py
  wodles/aws/aws-s3.py
Labels: enhancement, needs ruleset

#1105 Final re-work of AWS wodle as per #510
  CHANGELOG.md
  contrib/ossec-testing/runtests.py
  etc/rules/0350-amazon_rules.xml
  extensions/elasticsearch/wazuh-elastic6-template-alerts.json
  src/config/wmodules-aws.c
  src/config/wmodules-config.c
  src/init/inst-functions.sh
  src/init/update.sh
  src/wazuh_modules/wm_aws.c
  src/wazuh_modules/wm_aws.h
  wodles/aws/aws-s3.py
  wodles/aws/aws.py
Labels: enhancement, needs ruleset, stall

#1170 Fix concurrent agent connection by osquery integration
  src/wazuh_modules/wm_osquery_monitor.c
Labels: bug

#1174 Fixing update oval in legacy configuration
  CHANGELOG.md
  src/config/wmodules-vuln-detector.c
Labels: bug, vuln detector

#1166 Prevent some vulnerabilities from not being checked for Debian
  CHANGELOG.md
  src/wazuh_modules/wm_vuln_detector.c
Labels: bug, vuln detector

#1172 Create netsh-2018.cmd
  .gitignore
  CHANGELOG.md
  active-response/win/netsh-win-2016.cmd
  etc/templates/config/generic/ar-commands.template
  src/Makefile
  src/win32/ossec-installer.nsi
  src/win32/wazuh-installer.wxs
Labels: enhancement

#1182 Add active-response files to nsi and wxs files
  .gitignore
  CHANGELOG.md
  etc/templates/config/generic/ar-commands.template
  src/Makefile
  src/win32/ossec-installer.nsi
  src/win32/wazuh-installer.wxs
Labels: bug
