Repository wazuh/wazuh, pull requests merged in 2019-12, with the labels that each got.

#4294 [Logcollector] Fix SIGSEGV when using force_reload and the eventchannel format in UNIX systems
  src/logcollector/logcollector.c
Labels: bug, core/logcollector

#4394 Fix content_changes field on Windows when nodiff is configured on the monitored file
  src/syscheckd/seechanges.c
Labels: bug, core/fim, platform/windows

#4396 Fixed clearing report_changes database on Solaris
  src/shared/file_op.c
  src/syscheckd/run_check.c
Labels: bug, core/fim, platform/solaris
