Repository wazuh/wazuh, pull requests merged in 2021-12, with the labels that each got.

#7687 fix wrong macro to get the buffer length for getpwnam_r()
  src/shared/privsep_op.c
Labels: bug, core/shared, community

#11121 Fix Window agent unit tests on MinGW 10
  src/headers/file_op.h
  src/headers/sym_load.h
  src/unit_tests/client-agent/CMakeLists.txt
  src/unit_tests/shared/CMakeLists.txt
  src/unit_tests/shared/test_list_op.c
  src/unit_tests/syscheckd/CMakeLists.txt
  src/unit_tests/syscheckd/db/CMakeLists.txt
  src/unit_tests/syscheckd/test_create_db.c
Labels: bug, platform/windows, core/unit tests, release/4.3.0

#10942 Fixed warnings when compiling windows agent.
  src/shared/file_op.c
Labels: core/syscollector, platform/windows

#11021 Remove unused exceptions
  framework/wazuh/core/exception.py
Labels: enhancement, framework, cluster, API

#11118 Fix memory leak to avoid crash on winagent
  src/shared/syscheck_op.c
Labels: bug, core/agent, platform/windows, release/4.3.0

#11161 Initialize Blowfish encryption structure
  src/os_crypto/blowfish/bf_op.c
Labels: core/shared, coverity, release/4.3.0

#10906 Add necessary changes to start FIM dbsync based database
  architecture/FIM/db/class.puml
  src/Makefile
  src/syscheckd/create_db.c
  src/syscheckd/db/CMakeLists.txt
  src/syscheckd/db/include/commonDefs.h
  src/syscheckd/db/include/db.hpp
  src/syscheckd/db/include/fimDB.hpp
  src/syscheckd/db/include/fimDBHelper.hpp
  src/syscheckd/db/src/db.cpp
  src/syscheckd/db/src/fimDB.cpp
  src/syscheckd/db/tests/fimDBHelper/fimDBHelperTest.cpp
  src/syscheckd/db/tests/fimDBTests/fimDBImpTests.cpp
  src/syscheckd/fim_sync.c
  src/syscheckd/registry/registry.c
  src/syscheckd/run_check.c
  src/syscheckd/syscheck.c
  src/unit_tests/syscheckd/db/test_fim_db.c
Labels: core/fim

#11159 Fix duplicate values from hotfixes provider
  src/data_provider/cppcheckSuppress.txt
  src/data_provider/src/packages/packagesWindowsParserHelper.h
  src/data_provider/src/sysInfoWin.cpp
  src/data_provider/tests/sysInfoWin/sysInfoWin_test.cpp
Labels: bug, core/sysinfo, release/4.3.0

#10969 Creating new groups_hash column in the `agent` table of global.db
  src/wazuh_db/schema_global.sql
  src/wazuh_db/schema_global_upgrade_v4.sql
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
  src/wazuh_db/wdb_upgrade.c
Labels: enhancement, core/agent-groups

#10772 8691 os build windows incomplete syscollector
  src/data_provider/src/osinfo/sysOsInfoWin.cpp
  src/data_provider/src/osinfo/sysOsInfoWin.h
  src/shared/file_op.c
Labels: core/syscollector

#10773 Stop resetting the Wazuh manager when testing a custom ruleset with runtest.py
  ruleset/testing/runtests.py
Labels: enhancement, ruleset, rules

#11195 Update function OS_IsValidIP to support IPv4 and IPv6 protocols
  src/Makefile
  src/data_provider/tests/sysInfo/sysInfo_test.cpp
  src/headers/expression.h
  src/headers/shared.h
  src/headers/validate_op.h
  src/os_crypto/shared/keys.c
  src/shared/expression.c
  src/shared/validate_op.c
  src/unit_tests/analysisd/CMakeLists.txt
  src/unit_tests/analysisd/test_rule_list.c
  src/unit_tests/os_auth/CMakeLists.txt
  src/unit_tests/os_auth/test_auth_add.c
  src/unit_tests/os_auth/test_auth_parse.c
  src/unit_tests/os_auth/test_auth_validate.c
  src/unit_tests/os_crypto/shared/CMakeLists.txt
  src/unit_tests/os_crypto/shared/test_keys.c
  src/unit_tests/shared/CMakeLists.txt
  src/unit_tests/shared/test_expression.c
  src/unit_tests/shared/test_validate_op.c
  src/unit_tests/wrappers/externals/pcre2/pcre2_wrappers.c
  src/unit_tests/wrappers/wazuh/os_net/os_net_wrappers.c
  src/unit_tests/wrappers/wazuh/os_net/os_net_wrappers.h
  src/unit_tests/wrappers/wazuh/os_xml/os_xml_wrappers.c
  src/unit_tests/wrappers/wazuh/shared/expression_wrappers.c
  src/unit_tests/wrappers/wazuh/shared/expression_wrappers.h
  src/unit_tests/wrappers/wazuh/shared/validate_op_wrappers.c
  src/unit_tests/wrappers/wazuh/shared/validate_op_wrappers.h
  src/util/agent_control.c
Labels: enhancement, core/agent, core/remoted, core/auth

#11256 Adapt OS_IPFound and other functions to work with IPv6
  src/os_crypto/shared/keys.c
  src/shared/validate_op.c
  src/unit_tests/shared/test_validate_op.c
  src/unit_tests/wrappers/wazuh/os_net/os_net_wrappers.c
  src/wazuh_modules/wm_database.c
Labels: enhancement, core/agent, core/remoted, core/auth

#10873 Handling SIGTERM signal
  src/os_dbd/db_op.c
  src/os_dbd/main.c
Labels: enhancement

#11194 Fix AWS VPCFlow reparse option
  wodles/aws/aws_s3.py
Labels: bug, aws_integration, external_integrations

#11050 Update AWS integration unit tests
  wodles/aws/tests/test_aws.py
Labels: aws_integration, external_integrations, release/4.3.0

#11292 Fix journalctl commands in SCA policies
  ruleset/sca/sles/15/cis_sles15_linux.yml
  ruleset/sca/ubuntu/cis_ubuntu18-04.yml
  ruleset/sca/ubuntu/cis_ubuntu20-04.yml
Labels: bug, sca

#11262 Fix heap overrun in Vulnerability Detector
  src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
Labels: bug, core/vuln detector

#11294 Adding new columns for sync and group order
  src/wazuh_db/helpers/wdb_global_helpers.c
  src/wazuh_db/helpers/wdb_global_helpers.h
  src/wazuh_db/schema_global.sql
  src/wazuh_db/schema_global_upgrade_v4.sql
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
Labels: upgrade, core/db

#10822 Print ruleset warning messages in wazuh-logtest
  framework/scripts/wazuh-logtest.py
Labels: enhancement

#11243 Adapting all the required methods to migrate agent-groups files to Wazuh-DB
  src/addagent/manage_agents.h
  src/addagent/validate.c
  src/headers/agent_op.h
  src/os_auth/auth.c
  src/os_auth/auth.h
  src/os_auth/local-server.c
  src/os_auth/main-server.c
  src/remoted/manager.c
  src/shared/agent_op.c
  src/unit_tests/os_auth/CMakeLists.txt
  src/unit_tests/remoted/CMakeLists.txt
  src/wazuh_db/helpers/wdb_global_helpers.c
  src/wazuh_db/helpers/wdb_global_helpers.h
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
  src/wazuh_modules/wm_database.c
Labels: enhancement, core/db, core/agent-groups

#11278 Fix azure configuration parsing
  src/config/wmodules-azure.c
  src/wazuh_modules/wm_azure.c
Labels: core/configuration, azure_integration, external_integrations

#11231 Fix Google Cloud Storage folder filtering
  wodles/gcloud/buckets/bucket.py
  wodles/gcloud/pubsub/subscriber.py
Labels: gcp_integration, external_integrations

#11329 Increase sysinfo ports inode range
  src/data_provider/src/ports/iportWrapper.h
  src/data_provider/src/ports/portBSDWrapper.h
  src/data_provider/src/ports/portLinuxWrapper.h
  src/data_provider/src/ports/portWindowsWrapper.h
  src/data_provider/tests/sysInfoPorts/sysInfoPort_test.cpp
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_parser.c
  src/wazuh_db/wdb_syscollector.c
Labels: core/sysinfo, platform/linux

#11352 Wazuh Engine development environment
  src/engine/.gitignore
  src/engine/CMakeLists.txt
  src/engine/README.md
  src/engine/benchmark/CMakeLists.txt
  src/engine/benchmark/source/dummy_benchmark.cpp
  src/engine/cmake/CPM.cmake
  src/engine/docs/Doxyfile.in
  src/engine/docs/img/bottom_menu.png
  src/engine/docs/img/left_menu_cmake.png
  src/engine/docs/img/left_menu_tests.png
  src/engine/source/main.cpp
  src/engine/test/CMakeLists.txt
  src/engine/test/source/dummy_test.cpp
Labels: enhancement, core/cmake, core/engine

#11370 Fix file descriptor leak in Vulnerability Detector
  src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
  src/wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c
Labels: core/vuln detector, bug/descriptor leak

#10838 Standardize the use of the `only_logs_after` parameter in the external integration modules
  wodles/aws/aws_s3.py
  wodles/gcloud/buckets/bucket.py
  wodles/gcloud/tools.py
Labels: enhancement, aws_integration, gcp_integration

#11395 Fix memory leak in Vulnerability-Detector agent scan 4.3
  src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
Labels: bug, core/vuln detector, memory

#11126 Rework for Amazon Linux 2 SCA mapping and checks
  ruleset/sca/amazon/cis_amazon_linux_2.yml
Labels: sca, threatintel/PR, release/4.3.0

#11242 Rework of PR #10354- SCA RHEL 8 update and fix
  ruleset/sca/rhel/8/cis_rhel8_linux.yml
Labels: threatintel/PR, release/4.3.0

#11223 Rework PR 8977 - SLES12 & SLES15 - Add new sca files for MS IIS, Oracle Database 19c, MongoDB 3.6, Nginx, SQL Server and SLES
  ruleset/sca/sles/12/cis_sles12_linux.yml
  ruleset/sca/sles/15/cis_sles15_linux.yml
Labels: threatintel/PR, release/4.3.0

#11013 Rework of PRs #10025 and #10046 - Rules and Decoders for ESET Remote Administrator
  ruleset/decoders/0575-eset-remote_decoders.xml
  ruleset/rules/0925-eset-remote_rules.xml
  ruleset/testing/tests/eset.ini
Labels: threatintel/PR, release/4.3.0

#11117 Rework of PR #8292 - Deleted end pipe character at rules 60908 and 60884
  ruleset/rules/0585-win-application_rules.xml
  ruleset/testing/tests/win_application.ini
Labels: threatintel/PR, release/4.3.0

#11219 Revert for haproxy decoders
  ruleset/decoders/0535-haproxy_decoders.xml
Labels: threatintel/PR, release/4.3.0

#11245 Rework PR 8977 - Oracle Database 19c - Add new sca files for MS IIS, MongoDB 3.6, Nginx, SQL Server and SLES
  ruleset/sca/oracledb/cis_oracle_database_19c.yml
Labels: threatintel/PR, release/4.3.0

#11141 Revert of PR #10023 - PR: Decoders for AWS RDS through Cloudwatch
  ruleset/decoders/0570-aws-cloudwatch_decoders.xml
Labels: threatintel/PR, release/4.3.0

#11202 Revert for rules, decoder and ini of Cylance integration
  ruleset/decoders/0545-cylance_decoders.xml
  ruleset/rules/0730-cylance_rules.xml
  ruleset/testing/tests/cylance.ini
Labels: threatintel/PR, release/4.3.0

#11429 Review PR 10406 - Wazuh 420 sca rules centos7
  ruleset/sca/centos/7/cis_centos7_linux.yml
Labels: threatintel/PR, release/4.3.0

#11430 Review PR 9750 - PR: Changes to SCA: cis_ubuntu20-04.yml
  ruleset/sca/ubuntu/cis_ubuntu20-04.yml
Labels: threatintel/PR, release/4.3.0

#11431 Review of PR 7663 - 7662 - add SCA CIS policies for amazon linux 1
  ruleset/sca/amazon/cis_amazon_linux_1.yml
Labels: threatintel/PR, release/4.3.0

#11432 Review of PR 7663 - 7662 - add SCA CIS policies for Ubuntu 14
  ruleset/sca/ubuntu/cis_ubuntu14-04.yml
Labels: threatintel/PR, release/4.3.0

#11286 Rework of #10707 & 10369 - PR: Fix YAML issues in Solaris 11.4 SCA
  ruleset/sca/sunos/cis_solaris11.4.yml
Labels: threatintel/PR, release/4.3.0

#11383 Fix compilation/runtime common errors.
  src/syscheckd/db/src/db.cpp
  src/syscheckd/db/src/dbFileItem.cpp
  src/syscheckd/db/src/dbFileItem.hpp
  src/syscheckd/db/src/dbItem.hpp
Labels: core/fim

#11345 Implement the sync-agent-groups-get command
  src/wazuh_db/schema_global.sql
  src/wazuh_db/schema_global_upgrade_v4.sql
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
Labels: core/agent-groups

#11374 Dev support ipv6 fix
  src/analysisd/cleanevent.c
  src/headers/validate_op.h
  src/os_auth/auth.c
  src/os_auth/local-server.c
  src/os_auth/main-server.c
  src/os_crypto/shared/keys.c
  src/os_net/os_net.c
  src/remoted/secure.c
  src/remoted/syslog.c
  src/shared/validate_op.c
  src/unit_tests/client-agent/CMakeLists.txt
  src/unit_tests/client-agent/test_start_agent.c
  src/unit_tests/os_auth/test_auth_parse.c
  src/unit_tests/os_net/test_os_net.c
  src/unit_tests/shared/test_validate_op.c
Labels: enhancement, core/agent, core/remoted, core/auth

#11459 Implement set-agent-groups command
  src/os_crypto/sha256/sha256_op.c
  src/os_crypto/sha256/sha256_op.h
  src/wazuh_db/helpers/wdb_global_helpers.c
  src/wazuh_db/helpers/wdb_global_helpers.h
  src/wazuh_db/schema_global.sql
  src/wazuh_db/schema_global_upgrade_v4.sql
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
Labels: core/agent-groups

#11250 Rework PR 8977 - NginX - Add new sca files for MS IIS, MongoDB 3.6, Nginx, SQL Server and SLES
  ruleset/sca/applications/cis_iis_10.yml
Labels: threatintel/PR, release/4.3.0

#11480 Resolve SCA Amazon linux 2 issues
  ruleset/sca/amazon/cis_amazon_linux_2.yml
Labels: threatintel/PR

#11452 Review of PR 7663 - 7662 - add SCA CIS policies Ubuntu 16
  ruleset/sca/ubuntu/cis_ubuntu16-04.yml
Labels: threatintel/PR, release/4.3.0

#11248 Rework PR 8977 - NginX - Add new sca files for MS IIS, MongoDB 3.6, Nginx, SQL Server and SLES
  ruleset/sca/nginx/cis_nginx_1.yml
Labels: threatintel/PR

#11249 Rework PR 8977 - SQL Server 20216 - Add new sca files for MS IIS, MongoDB 3.6, Nginx, SQL Server and SLES
  ruleset/sca/applications/cis_sqlserver_2016.yml
Labels: threatintel/PR, release/4.3.0

#11453 Review of PR 7663 - add SCA CIS policies Ubuntu 18
  ruleset/sca/ubuntu/cis_ubuntu18-04.yml
Labels: threatintel/PR, release/4.3.0

#11247 Rework PR 8977 - MongoDB 3.6 - Add new sca files for MS IIS, Oracle Database 19c, MongoDB 3.6, Nginx, SQL Server and SLES
  ruleset/sca/mongodb/cis_mongodb_36.yml
Labels: threatintel/PR, release/4.3.0

#11154 Rework of PR #9085 - 8071 add postgre sql sca
  ruleset/sca/applications/cis_postgre-sql-13.yml
Labels: threatintel/PR, release/4.3.0

#11454 Review or pr 10558 - PR: Adapt CIS benchmark for macOS Big Sur
  ruleset/sca/darwin/20/cis_apple_macOS_11.1.yml
Labels: threatintel/PR, release/4.3.0

#11100 Rework of PRs #10161 & # 10502 - Rules and Decoders for FortiNet Products
  ruleset/decoders/0100-fortigate_decoders.xml
  ruleset/decoders/0101-fortiddos_decoders.xml
  ruleset/decoders/0102-fortimail_decoders.xml
  ruleset/decoders/0103-fortiauth_decoders.xml
  ruleset/rules/0390-fortiddos_rules.xml
  ruleset/rules/0391-fortigate_rules.xml
  ruleset/rules/0392-fortimail_rules.xml
  ruleset/rules/0393-fortiauth_rules.xml
  ruleset/testing/tests/fortiauth.ini
  ruleset/testing/tests/fortiddos.ini
  ruleset/testing/tests/fortigate.ini
  ruleset/testing/tests/fortimail.ini
Labels: threatintel/PR, release/4.3.0

#11137 Rework of #9355 - Decoders and Rules for Palo Alto
  ruleset/decoders/0505-paloalto_decoders.xml
  ruleset/rules/0700-paloalto_rules.xml
  ruleset/testing/tests/paloalto.ini
Labels: threatintel/PR, release/4.3.0

#11143 Revert of PR #10012 - 10012 update apache ruleset
  ruleset/decoders/0025-apache_decoders.xml
  ruleset/rules/0250-apache_rules.xml
  ruleset/testing/tests/apache.ini
Labels: threatintel/PR, release/4.3.0

#11601 Fix Wazuh API PID file race condition
  api/scripts/wazuh-apid.py
Labels: bug, API

#11600 Fix AWS integration's Cisco Umbrella module
  wodles/aws/aws_s3.py
Labels: aws_integration, external_integrations

#10870 Support the use of the Azure integration module in Linux agents
  src/config/wmodules-azure.c
  src/config/wmodules-config.c
  src/init/inst-functions.sh
  src/wazuh_modules/wm_azure.c
  src/wazuh_modules/wm_azure.h
Labels: enhancement, azure_integration, external_integrations

#10478 Handle more exceptions in the wodles and remove duplicated functions from framework file
  framework/wazuh/core/common.py
  wodles/utils.py
Labels: enhancement, framework, external_integrations

#11608 Fix `--reparse` option in AWS' VPCFlow and Config modules
  wodles/aws/aws_s3.py
Labels: aws_integration, external_integrations

#11471 Change FIM scan to use DBSync transactions.
  src/error_messages/error_messages.h
  src/syscheckd/create_db.c
  src/syscheckd/db/include/db.h
  src/syscheckd/db/include/fimCommonDefs.h
  src/syscheckd/db/src/db.cpp
  src/syscheckd/db/src/fimDB.hpp
  src/syscheckd/run_check.c
  src/syscheckd/syscheck.h
Labels: core/fim

#11576 Moving the client.keys synchronization mechanism with wazuh-db from the synchronization module to authd in the master nodes
  src/os_auth/auth.c
  src/os_auth/auth.h
  src/os_auth/main-server.c
  src/wazuh_db/helpers/wdb_global_helpers.c
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_modules/wm_database.c
  src/wazuh_modules/wm_database.h
Labels: enhancement, core/auth, core/modulesd, core/agent-groups

#11451 Created a new backup mechanism for Wazuh-DB to save information from global.db
  etc/ossec-local.conf
  etc/ossec-server.conf
  etc/ossec.conf
  etc/templates/config/generic/wdb.template
  src/config/authd-config.h
  src/config/config.c
  src/config/config.h
  src/config/wazuh_db-config.c
  src/config/wazuh_db-config.h
  src/headers/defs.h
  src/headers/string_op.h
  src/init/inst-functions.sh
  src/wazuh_db/main.c
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
Labels: enhancement, core/db
