Repository wazuh/wazuh, pull requests merged in 2022-01, with the labels that each got.

#11644 Remove unnecessary AWS API calls when the last log processed is earlier than the `only_logs_after` value in VPCFlow and Config modules
  wodles/aws/aws_s3.py
Labels: aws_integration, external_integrations

#11649 Decode Pub/Sub messages before sending them to `analysisd`
  wodles/gcloud/pubsub/subscriber.py
Labels: gcp_integration, qa/report, external_integrations

#11144 Revert of PR #9540 - New decoders for Cisco IOS
  ruleset/decoders/0065-cisco-ios_decoders.xml
Labels: threatintel/PR, release/4.3.0

#11156 Revert of #8842 - 8301 improve ms dhcp ipv4 decoder
  ruleset/decoders/0380-windows_decoders.xml
Labels: threatintel/PR, release/4.3.0

#11288 Revert of PR #9030 - Added icinga rules, decoders and .ini
  ruleset/decoders/0530-icinga_decoders.xml
  ruleset/rules/0715-icinga_rules.xml
  ruleset/testing/tests/icinga.ini
Labels: rules, decoders, threatintel/PR, release/4.3.0

#11298 Revert PR #10458 - Decoders and Rules for TrendMicro Cloud One
  ruleset/decoders/0580-trendmicro-cloud_decoders.xml
  ruleset/rules/0930-trendmicro-cloud_rules.xml
  ruleset/testing/tests/trendmicro-cloud-one.ini
Labels: rules, decoders, threatintel/PR, release/4.3.0

#11284 Rework of #9366 - 9342 add aws eks decoders
  ruleset/decoders/0565-aws-eks-authenticator_decoders.xml
Labels: threatintel/PR, release/4.3.0

#11491 Replace the old update agent group method with the new set agent group implementation.
  src/os_auth/main-server.c
  src/remoted/manager.c
  src/wazuh_db/wdb.h
Labels: enhancement

#11749 Inserting legacy agent groups files in Wazuh-DB at startup
  src/wazuh_db/helpers/wdb_global_helpers.h
  src/wazuh_modules/wm_database.c
Labels: enhancement, core/db, core/agent-groups

#11739 Finalize all statements in cache before creating a database backup
  src/config/wazuh_db-config.c
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
Labels: core/db, bug/devel

#11736 Fix Windows installer issues
  src/os_xml/os_xml_writer.c
  src/win32/InstallerScripts.vbs
  src/win32/ReplaceConf.vbs
  src/win32/wazuh-installer.wxs
Labels: bug, core/agent, platform/windows, installer

#11760 Adding a getconfig command for Wazuh-DB
  src/config/wazuh_db-config.c
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_parser.c
Labels: enhancement, core/db

#11372 Number of groups per agent reduction
  src/headers/defs.h
  src/headers/string_op.h
  src/os_auth/auth.c
  src/shared/string_op.c
  src/wazuh_db/helpers/wdb_global_helpers.c
  src/wazuh_modules/wm_database.c
Labels: core/auth

#11756 Add support for getting CPU frequency on Raspberry PI
  src/data_provider/cppcheckSuppress.txt
  src/data_provider/src/sharedDefs.h
  src/data_provider/src/sysInfoLinux.cpp
Labels: bug, core/syscollector, platform/raspberry pi, core/sysinfo

#11584 Updated deprecated MITRE ids in 0015-ossec_rules.xml
  ruleset/rules/0015-ossec_rules.xml
Labels: threatintel/PR

#11585 Updated deprecated MITRE ids in 0020-syslog_rules.xml
  ruleset/rules/0020-syslog_rules.xml
Labels: threatintel/PR

#11593 Updated deprecated MITRE ids in 0065-pix_rules.xml
  ruleset/rules/0065-pix_rules.xml
Labels: threatintel/PR

#11594 Updated deprecated MITRE ids in 0070-netscreenfw_rules.xml
  ruleset/rules/0070-netscreenfw_rules.xml
Labels: threatintel/PR

#11698 Updated deprecated MITRE ids in 0220-msauth_rules.xml
  ruleset/rules/0220-msauth_rules.xml
Labels: threatintel/PR

#11700 Updated deprecated MITRE ids in 0270-web_appsec_rules.xml
  ruleset/rules/0270-web_appsec_rules.xml
Labels: threatintel/PR

#11701 Updated deprecated MITRE ids in 0275-squid_rules.xml
  ruleset/rules/0275-squid_rules.xml
Labels: threatintel/PR

#11704 Updated deprecated MITRE ids in 0320-clam_av_rules.xml
  ruleset/rules/0320-clam_av_rules.xml
Labels: threatintel/PR

#11705 Updated deprecated MITRE ids in 0345-netscaler_rules.xml
  ruleset/rules/0345-netscaler_rules.xml
Labels: threatintel/PR

#11707 Updated deprecated MITRE ids in 0360-serv-u_rules.xml
  ruleset/rules/0360-serv-u_rules.xml
Labels: threatintel/PR

#11711 Updated deprecated MITRE ids in 0391-fortigate_rules.xml
  ruleset/rules/0391-fortigate_rules.xml
Labels: threatintel/PR

#11602 Updated deprecated MITRE ids in 0435-ms_logs_rules.xml
  ruleset/rules/0435-ms_logs_rules.xml
Labels: threatintel/PR

#11713 Updated deprecated MITRE ids in 0545-osquery_rules.xml
  ruleset/rules/0545-osquery_rules.xml
Labels: threatintel/PR

#11714 Updated deprecated MITRE ids in 0560-docker_integration_rules.xml
  ruleset/rules/0560-docker_integration_rules.xml
Labels: threatintel/PR

#11715 Updated deprecated MITRE ids in 0565-ms_ipsec_rules.xml
  ruleset/rules/0565-ms_ipsec_rules.xml
Labels: threatintel/PR

#11716 Updated deprecated MITRE ids in 0580-win-security_rules.xml
  ruleset/rules/0580-win-security_rules.xml
Labels: threatintel/PR

#11717 Updated deprecated MITRE ids in 0585-win-application_rules.xml
  ruleset/rules/0585-win-application_rules.xml
Labels: threatintel/PR

#11718 Updated deprecated MITRE ids in 0590-win-system_rules.xml
  ruleset/rules/0590-win-system_rules.xml
Labels: threatintel/PR

#11719 Updated deprecated MITRE ids in 0601-win-vipre_rules.xml
  ruleset/rules/0601-win-vipre_rules.xml
Labels: threatintel/PR

#11720 Updated deprecated MITRE ids in 0610-win-ms_logs_rules.xml
  ruleset/rules/0610-win-ms_logs_rules.xml
Labels: threatintel/PR

#11721 Updated deprecated MITRE ids in 0625-cisco-asa_rules.xml
  ruleset/rules/0625-cisco-asa_rules.xml
Labels: threatintel/PR

#11722 Updated deprecated MITRE ids in 0905-cisco-ftd_rules.xml
  ruleset/rules/0905-cisco-ftd_rules.xml
Labels: threatintel/PR

#11612 Updated deprecated MITRE ids in 0110-ms_dhcp_rules.xml
  ruleset/rules/0110-ms_dhcp_rules.xml
Labels: threatintel/PR

#11699 Updated deprecated MITRE ids in 0265-php_rules.xml
  ruleset/rules/0265-php_rules.xml
Labels: threatintel/PR

#11710 Updated deprecated MITRE ids in 0365-auditd_rules.xml
  ruleset/rules/0365-auditd_rules.xml
Labels: threatintel/PR

#11768 Removing deprecated group folders from installation and upgrade scripts
  src/init/inst-functions.sh
  src/init/update.sh
Labels: upgrade, core/agent-groups

#11771 Restoring the agents database creation to the database synchronization module to avoid errors in authd
  src/os_auth/main-server.c
  src/wazuh_db/helpers/wdb_global_helpers.c
  src/wazuh_db/wdb.c
  src/wazuh_modules/wm_database.c
  src/wazuh_modules/wm_database.h
Labels: core/db, core/auth, core/modulesd

#11741 src/addagent/validate.c: remove unused include file
  src/addagent/validate.c
Labels: community

#11763 Fix bug in fim_db_remove_path
  src/syscheckd/db/src/file.cpp
  src/syscheckd/db/src/fimDBHelper.hpp
Labels: bug/devel

#11746 Create global db pre and post snapshots on upgrades
  src/headers/defs.h
  src/wazuh_db/main.c
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
  src/wazuh_db/wdb_upgrade.c
Labels: core/db

#11764 Fix bug on fim_db_file_pattern
  src/syscheckd/db/src/file.cpp
  src/syscheckd/db/src/fimDBHelper.hpp
  src/syscheckd/db/src/fimDBUtils.hpp
Labels: bug/devel

#11778 Added log messages, hide wazuh-db configuration
  etc/ossec-local.conf
  etc/ossec-server.conf
  etc/ossec.conf
  etc/templates/config/generic/wdb.template
  src/init/inst-functions.sh
  src/wazuh_db/main.c
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
  src/wazuh_db/wdb_upgrade.c
Labels: enhancement, core/db

#11122 Revert for Sophos UTM firewall rules
  ruleset/rules/0416-sophos-utm-firewall_rules.xml
  ruleset/testing/tests/sophos-utm-firewall.ini
Labels: rules, threatintel/PR, release/4.3.0

#11342 Rework of #9323 - Detect MITRE's Carbanak step 9.A
  ruleset/rules/0870-sysmon_id_8.xml
Labels: threatintel/PR, release/4.3.0

#11212 Rework of PR #8609 - 8395 wmi discovery rules
  ruleset/rules/0575-win-base_rules.xml
Labels: threatintel/PR, release/4.3.0

#11191 Rework of #8473 - Add rules for GCP VPC Storage access logs
  ruleset/rules/0690-gcp_rules.xml
  ruleset/testing/tests/gcp.ini
Labels: threatintel/PR

#11214 Rework of #9145 - Rules id 91601 and 91602 are duplicated
  ruleset/rules/0915-win-powershell_rules.xml
Labels: threatintel/PR, release/4.3.0

#11232 Rework of #9018 - Updated proftd decoder and added more sample logs
  ruleset/decoders/0230-proftpd_decoders.xml
  ruleset/rules/0175-proftpd_rules.xml
  ruleset/testing/tests/proftpd.ini
Labels: threatintel/PR, release/4.3.0

#11344 Rework of #9020 - Updated exim4 rules, decoders and .ini to support new logs
  ruleset/decoders/0445-exim_decoders.xml
  ruleset/rules/0515-exim_rules.xml
  ruleset/testing/tests/exim.ini
Labels: threatintel/PR, release/4.3.0

#11369 Rework PR #8975 - Fixed MS Logs rule 83200 bug
  ruleset/rules/0435-ms_logs_rules.xml
Labels: rules, threatintel/PR, release/4.3.0

#11357 Rework of #10428 - PR: Create rules and decoders for Wazuh API events
  ruleset/decoders/0007-wazuh-api_decoders.xml
  ruleset/decoders/0515-wazuh-api-decoders.xml
  ruleset/rules/0017-wazuh-api_rules.xml
  ruleset/rules/0710-wazuh-api-rules.xml
  ruleset/testing/tests/api.ini
  src/init/wazuh/deprecated_ruleset.txt
Labels: threatintel/PR, release/4.3.0

#11815 Add variable with status of previous iteration of `local_integrity`
  framework/wazuh/core/cluster/master.py
Labels: bug, cluster

#11274 Rework of PR #9238 - OracleDB 12c Integration
  ruleset/decoders/0560-oracledb_decoders.xml
  ruleset/rules/0920-oracledb_rules.xml
Labels: threatintel/PR, release/4.3.0

#11177 Rework of #8155 - 8155 create aws s3 ruleset
  ruleset/rules/0350-amazon_rules.xml
  ruleset/testing/tests/aws_s3_access.ini
Labels: threatintel/PR, release/4.3.0

#11390 Rework of #9312 - Detection rules for registry persistence
  ruleset/rules/0860-sysmon_id_13.xml
Labels: threatintel/PR, release/4.3.0

#11748 Issue 11737 share download group deprecation
  src/Makefile
  src/os_auth/main-server.c
  src/remoted/manager.c
  src/remoted/shared_download.c
  src/remoted/shared_download.h
  src/unit_tests/remoted/test_manager.c
  src/unit_tests/wrappers/wazuh/remoted/shared_download_wrappers.c
  src/unit_tests/wrappers/wazuh/remoted/shared_download_wrappers.h
  src/wazuh_db/helpers/wdb_global_helpers.c
  src/wazuh_db/helpers/wdb_global_helpers.h
  src/wazuh_db/schema_global.sql
  src/wazuh_db/schema_global_upgrade_v4.sql
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
  src/wazuh_modules/wm_database.c
Labels: enhancement, core/agent-groups

#11306 Rework of #9266 - Refactor Carbanak related rules filenames to use data source
  ruleset/rules/0800-sysmon_id_1.xml
  ruleset/rules/0810-sysmon_id_3.xml
  ruleset/rules/0820-sysmon_id_7.xml
  ruleset/rules/0830-sysmon_id_11.xml
  ruleset/rules/0840-win_event_channel.xml
  ruleset/rules/0850-audit_rules.xml
  ruleset/testing/tests/audit_lateral.ini
  ruleset/testing/tests/audit_recon.ini
  ruleset/testing/tests/audit_scp.ini
Labels: threatintel, release/4.3.0

#11795 Rework of #10476 - PR: Update NextCloud rules
  ruleset/rules/0630-nextcloud_rules.xml
  ruleset/testing/tests/nextcloud.ini
Labels: threatintel/PR, release/4.3.0

#11289 Rework of PR #8285 - Adding rules for Hafnium related MS Exchange vulnerabilities
  ruleset/decoders/0520-msexchange-log-decoders.xml
  ruleset/rules/0910-ms-exchange-proxylogon_rules.xml
  ruleset/testing/tests/exchange.ini
Labels: threatintel, threatintel/PR

#11388 Rework of #10768 - PR: Merge macos-sshd ruleset into sshd ruleset
  ruleset/decoders/0310-ssh_decoders.xml
  ruleset/rules/0095-sshd_rules.xml
  ruleset/testing/tests/sshd.ini
  ruleset/testing/tests/test_features.ini
Labels: threatintel/PR, release/4.3.0

#11405 Rework of #9194 - MITRE: Changes to mapping from Command and Control
  ruleset/rules/0265-php_rules.xml
  ruleset/testing/tests/php.ini
Labels: threatintel/PR, release/4.3.0

#11323 Rework of PR #9041 - Gitlab v12 integration
  ruleset/decoders/0540-gitlab_decoders.xml
  ruleset/rules/0770-gitlab_rules.xml
  ruleset/testing/tests/gitlab.ini
Labels: threatintel, threatintel/PR

#11810 Adding the global group hash methods and cache for cluster syncronization
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_integrity.c
Labels: core/db, core/agent-groups

#11809 Adapt sync_agent_groups_get for synchronization mechanism 2.0
  src/wazuh_db/schema_global.sql
  src/wazuh_db/schema_global_upgrade_v4.sql
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
Labels: core/db, core/agent-groups

#11835 Fix an argument injection hazard in the Pagerduty integration script
  integrations/pagerduty
Labels: bug, core/integratord, operations, external_integrations

#11807 Added get-groups-integrity command
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
Labels: enhancement, core/db, core/agent-groups

#11863 Fix memory leaks in the Vulnerability Detector's feeds parser
  src/unit_tests/wazuh_modules/vulnerability_detector/test_wm_vuln_detector.c
  src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
Labels: core/vuln detector, bug/devel, memory

#11853 Unit Tests for the `get_agent_group` function
  src/unit_tests/shared/CMakeLists.txt
  src/unit_tests/shared/test_agent_op.c
Labels: qa, core/db, core/modulesd, core/unit tests, core/agent-groups

#11869 Dev 11754 - Wazuh-db `get-config` unit test
  src/unit_tests/wazuh_db/CMakeLists.txt
  src/unit_tests/wazuh_db/test_wdb.c
  src/unit_tests/wazuh_db/test_wdb_parser.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_wrappers.h
  src/wazuh_db/wdb_parser.c
Labels: core/db, core/unit tests

#11827 Update 4.3 changelog with latest ruleset changes
  CHANGELOG.md
Labels: threatintel

#11877 Unit tests - Fixing unit tests for `lookfor_agent_group` that now use wazuh-db instead shared-download
  src/unit_tests/remoted/CMakeLists.txt
  src/unit_tests/remoted/test_manager.c
  src/unit_tests/wrappers/wazuh/shared/agent_op_wrappers.c
  src/unit_tests/wrappers/wazuh/shared/agent_op_wrappers.h
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_helpers_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_helpers_wrappers.h
Labels: core/remoted, core/unit tests

#11878 Add necessary changes on FIMDB
  src/error_messages/error_messages.h
  src/syscheckd/cppcheckSuppress.txt
  src/syscheckd/src/db/CMakeLists.txt
  src/syscheckd/src/db/include/db.h
  src/syscheckd/src/db/src/db.cpp
  src/syscheckd/src/db/src/file.cpp
  src/syscheckd/src/db/src/fimDB.cpp
  src/syscheckd/src/db/src/fimDB.hpp
  src/syscheckd/src/db/src/registry.cpp
  src/syscheckd/src/db/tests/db/ComponentTest/fileInterface/CMakeLists.txt
  src/syscheckd/src/db/tests/db/FIMDB/fimDBTests/fimDBImpTests.cpp
  src/syscheckd/src/db/tests/db/FIMDB/fimDBTests/fimDBImpTests.hpp
  src/syscheckd/src/main.c
Labels: core/fim

#11833 Add process start time to JSON object (macOS)
  src/data_provider/src/sysInfoMac.cpp
Labels: core/sysinfo

#11837 Fix of tunnel/VPN interfaces, in networks data provider.
  src/data_provider/src/network/networkLinuxWrapper.h
  src/shared_modules/utils/networkUnixHelper.h
Labels: core/sysinfo

#11885 Adding new mechanisms for global database error management during the upgrade
  src/unit_tests/wazuh_db/test_wdb_upgrade.c
  src/wazuh_db/main.c
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_parser.c
  src/wazuh_db/wdb_upgrade.c
Labels: enhancement, core/db

#11873 Added wdb_integrity tests for group hash
  src/unit_tests/wazuh_db/CMakeLists.txt
  src/unit_tests/wazuh_db/test_wdb_integrity.c
  src/wazuh_db/wdb_integrity.c
Labels: core/db, core/unit tests

#10929 Add issue template for the external integrations
  .github/ISSUE_TEMPLATE/external-integrations.md
Labels: external_integrations

#11385 Creation of the catalog base
  src/engine/.gitignore
  src/engine/CMakeLists.txt
  src/engine/source/catalog/CMakeLists.txt
  src/engine/source/catalog/Catalog.cpp
  src/engine/source/catalog/Catalog.hpp
  src/engine/source/catalog/catalogSharedDef.hpp
  src/engine/source/catalog/storageDriver/StorageDriverInterface.hpp
  src/engine/source/catalog/storageDriver/disk/DiskStorage.cpp
  src/engine/source/catalog/storageDriver/disk/DiskStorage.hpp
  src/engine/source/catalog/yml_to_json.hpp
  src/engine/test/CMakeLists.txt
  src/engine/test/source/catalog/CMakeLists.txt
  src/engine/test/source/catalog/Catalog_json_assets.hpp
  src/engine/test/source/catalog/Catalog_test.cpp
  src/engine/test/source/catalog/Catalog_test.hpp
  src/engine/test/source/catalog/storageDriver/disk/DiskStorage_test.cpp
Labels: core/engine

#11399 11339 builder linker engine
  src/engine/CMakeLists.txt
  src/engine/source/builder/builder.hpp
  src/engine/source/builder/builders/check_stage.hpp
  src/engine/source/builder/builders/condition.hpp
  src/engine/source/builder/builders/condition_value.hpp
  src/engine/source/builder/builders/decoder.hpp
  src/engine/source/builder/builders/file_output.hpp
  src/engine/source/builder/builders/filter.hpp
  src/engine/source/builder/builders/helper_exists.hpp
  src/engine/source/builder/builders/map.hpp
  src/engine/source/builder/builders/map_reference.hpp
  src/engine/source/builder/builders/map_value.hpp
  src/engine/source/builder/builders/normalize_stage.hpp
  src/engine/source/builder/builders/output.hpp
  src/engine/source/builder/builders/rule.hpp
  src/engine/source/builder/connectable.hpp
  src/engine/source/builder/include_builders.hpp
  src/engine/source/builder/outputs/file_output.hpp
  src/engine/source/builder/syntax.hpp
  src/engine/source/graph/graph.hpp
  src/engine/source/json/json.hpp
  src/engine/test/CMakeLists.txt
  src/engine/test/source/builder/CMakeLists.txt
  src/engine/test/source/builder/builder_test.cpp
  src/engine/test/source/builder/builder_test.hpp
  src/engine/test/source/builder/builders/check_stage_test.cpp
  src/engine/test/source/builder/builders/condition_test.cpp
  src/engine/test/source/builder/builders/condition_value_test.cpp
  src/engine/test/source/builder/builders/decoder_test.cpp
  src/engine/test/source/builder/builders/file_output_test.cpp
  src/engine/test/source/builder/builders/filter_test.cpp
  src/engine/test/source/builder/builders/helper_exists_test.cpp
  src/engine/test/source/builder/builders/map_reference_test.cpp
  src/engine/test/source/builder/builders/map_test.cpp
  src/engine/test/source/builder/builders/map_value_test.cpp
  src/engine/test/source/builder/builders/normalize_stage_test.cpp
  src/engine/test/source/builder/builders/output_test.cpp
  src/engine/test/source/builder/builders/rule_test.cpp
  src/engine/test/source/builder/outputs/CMakeLists.txt
  src/engine/test/source/builder/outputs/file_output_test.cpp
  src/engine/test/source/builder/test_utils.hpp
  src/engine/test/source/graph/CMakeLists.txt
  src/engine/test/source/graph/graph_test.cpp
  src/engine/test/source/graph/graph_test.hpp
  src/engine/test/source/json/CMakeLists.txt
  src/engine/test/source/json/json_test.cpp
Labels: core/engine

#11934 Improve belongs update
  src/headers/agent_op.h
  src/remoted/manager.c
  src/shared/agent_op.c
  src/unit_tests/remoted/CMakeLists.txt
  src/unit_tests/remoted/test_manager.c
  src/unit_tests/wrappers/wazuh/shared/agent_op_wrappers.c
  src/unit_tests/wrappers/wazuh/shared/agent_op_wrappers.h
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_helpers_wrappers.c
  src/wazuh_db/helpers/wdb_global_helpers.c
  src/wazuh_db/helpers/wdb_global_helpers.h
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
  src/wazuh_modules/wm_database.c
Labels: enhancement, core/agent-groups

#11883 Adapt wdb remove group
  src/unit_tests/wazuh_db/test_wdb_global_helpers.c
  src/unit_tests/wazuh_db/test_wdb_global_parser.c
  src/wazuh_db/helpers/wdb_global_helpers.c
  src/wazuh_db/helpers/wdb_global_helpers.h
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
Labels: core/agent-groups

#11416 11340 new engine router
  src/engine/benchmark/CMakeLists.txt
  src/engine/benchmark/source/router/CMakeLists.txt
  src/engine/benchmark/source/router/router_bench.cpp
  src/engine/source/router/router.hpp
  src/engine/test/CMakeLists.txt
  src/engine/test/source/router/CMakeLists.txt
  src/engine/test/source/router/router_test.cpp
  src/engine/test/source/router/router_test.hpp
Labels: core/engine

#11953 Unit test of get_groups_integrity
  src/unit_tests/wazuh_db/CMakeLists.txt
  src/unit_tests/wazuh_db/test_wdb_global.c
  src/unit_tests/wazuh_db/test_wdb_global_parser.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_wrappers.h
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_wrappers.h
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
Labels: core/db, core/unit tests

#11905 Create component tests for interface between c and c++ for FIMDB
  architecture/FIM/db/class.puml
  src/syscheckd/cppcheckSuppress.txt
  src/syscheckd/src/db/include/db.hpp
  src/syscheckd/src/db/src/db.cpp
  src/syscheckd/src/db/src/dbRegistryKey.cpp
  src/syscheckd/src/db/src/dbRegistryValue.cpp
  src/syscheckd/src/db/src/dbRegistryValue.hpp
  src/syscheckd/src/db/src/fimDB.cpp
  src/syscheckd/src/db/src/fimDB.hpp
  src/syscheckd/src/db/src/registry.cpp
  src/syscheckd/src/db/tests/CMakeLists.txt
  src/syscheckd/src/db/tests/db/ComponentTest/dbInterface/CMakeLists.txt
  src/syscheckd/src/db/tests/db/ComponentTest/dbInterface/dbTest.cpp
  src/syscheckd/src/db/tests/db/ComponentTest/dbInterface/dbTest.h
  src/syscheckd/src/db/tests/db/ComponentTest/dbInterface/main.cpp
  src/syscheckd/src/db/tests/db/FIMDB/fimDBTests/fimDBImpTests.cpp
  src/syscheckd/src/db/tests/db/FIMDB/fimDBTests/fimDBImpTests.hpp
Labels: core/fim

#11874 Adding unit tests for new Wazuh-DB backup commands
  src/unit_tests/wazuh_db/CMakeLists.txt
  src/unit_tests/wazuh_db/test_wdb_global.c
  src/unit_tests/wazuh_db/test_wdb_global_parser.c
  src/unit_tests/wazuh_db/test_wdb_parser.c
  src/unit_tests/wrappers/externals/cJSON/cJSON_wrappers.c
  src/unit_tests/wrappers/externals/cJSON/cJSON_wrappers.h
  src/unit_tests/wrappers/wazuh/shared/shared.cmake
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_wrappers.h
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_wrappers.h
  src/wazuh_db/wdb_global.c
Labels: core/db, core/unit tests

#11884 Adding UT for Wazuh-DB methods with groups hash and CSV string
  src/unit_tests/wazuh_db/CMakeLists.txt
  src/unit_tests/wazuh_db/test_wdb_global.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_wrappers.h
  src/wazuh_db/wdb.h
Labels: core/db, core/unit tests

#11964 UT cases for get_agent_max_group_priority
  src/unit_tests/wazuh_db/test_wdb_global.c
  src/wazuh_db/wdb_global.c
Labels: core/db, core/unit tests

#11895 Added UT cases for select groups belong
  src/unit_tests/wazuh_db/CMakeLists.txt
  src/unit_tests/wazuh_db/test_wdb_global.c
  src/unit_tests/wazuh_db/test_wdb_global_helpers.c
  src/unit_tests/wazuh_db/test_wdb_global_parser.c
  src/unit_tests/wrappers/externals/cJSON/cJSON_wrappers.h
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_wrappers.h
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_wrappers.h
  src/wazuh_db/helpers/wdb_global_helpers.h
  src/wazuh_db/wdb_parser.c
Labels: core/db, core/unit tests

#10978 Configure enrollment when using deployment variables
  src/init/register_configure_agent.sh
  src/win32/InstallerScripts.vbs
  src/win32/wazuh-installer.wxs
Labels: packages

#11955 Unit tests - Tests for `wdb_close`, `wdb_leave` and `wdb_finalize_all_statements`
  src/unit_tests/wazuh_db/CMakeLists.txt
  src/unit_tests/wazuh_db/test_wdb.c
  src/wazuh_db/wdb.c
Labels: core/db, core/unit tests

#11975 UT for set-agent-groups parser
  src/unit_tests/wazuh_db/CMakeLists.txt
  src/unit_tests/wazuh_db/test_wdb_global_parser.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_wrappers.h
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
Labels: core/db, core/unit tests

#11966 Adding unit test cases for functions related to the upgrade of the global database
  src/unit_tests/wazuh_db/CMakeLists.txt
  src/unit_tests/wazuh_db/test_wdb_global.c
  src/unit_tests/wazuh_db/test_wdb_upgrade.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_wrappers.h
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_metadata_wrappers.c
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_metadata.c
  src/wazuh_db/wdb_upgrade.c
Labels: core/db, core/unit tests

#11999 Adding unit test coverage for function `wdb_check_backup_enabled`
  src/unit_tests/wazuh_db/test_wdb.c
  src/wazuh_db/main.c
  src/wazuh_db/wdb.c
Labels: core/db, core/unit tests

#11970 Remove every mention to agent-groups in the integrity task
  framework/wazuh/core/cluster/cluster.json
  framework/wazuh/core/cluster/cluster.py
  framework/wazuh/core/cluster/tests/test_cluster.py
  framework/wazuh/core/cluster/tests/test_utils.py
  framework/wazuh/core/cluster/worker.py
Labels: framework, cluster

#11965 Dev 11754 unit testing for wdb_ global_helpers
  src/unit_tests/wazuh_db/CMakeLists.txt
  src/unit_tests/wazuh_db/test_wdb_global_helpers.c
Labels: core/db, core/unit tests

#12028 Add set_agent_group and set_agent_group_context UT
  src/unit_tests/wazuh_db/test_wdb_global.c
  src/wazuh_db/wdb_global.c
Labels: core/db, core/unit tests

#12005 Fix the exceed in the specified groups per agents
  framework/wazuh/core/agent.py
  framework/wazuh/core/exception.py
Labels: bug, framework, cluster
