Repository wazuh/wazuh, pull requests merged in 2022-10, with the labels that each got.

#15007 Fix remote policy detection in SCA
  src/config/wmodules-sca.c
  src/unit_tests/wazuh_modules/sca/CMakeLists.txt
  src/unit_tests/wazuh_modules/sca/test_wm_sca.c
Labels: type/bug, platform/windows, module/sca, platform/unix

#15023 Fix agent upgrade module settings parser to set a default CA file
  src/config/wmodules-agent-upgrade.c
Labels: type/bug, module/upgrade/wpk, module/upgrade, type/bug/regression

#14985 Update Ubuntu version for RTR tests
  src/ci/utils.py
Labels: type/bug

#15072 Wazuh api extract hash
  ruleset/decoders/0007-wazuh-api_decoders.xml
  ruleset/testing/tests/api.ini
Labels: feed/decoders, team/threatintel

#14981 Fix data race conditions reported by ThreadSanitizer
  src/Makefile
  src/headers/sec.h
  src/headers/shared.h
  src/os_crypto/shared/keys.c
  src/os_crypto/shared/msgs.c
  src/remoted/manager.c
  src/remoted/secure.c
  src/unit_tests/remoted/test_secure.c
Labels: type/bug, module/agent, module/remote

#15103 Added upgrade tests release template
  .github/ISSUE_TEMPLATE/release-upgrade-tests.md
Labels: Hacktoberfest-accepted

#15105 Create release-selinux-tests.md template to manage SELinux tests
  .github/ISSUE_TEMPLATE/release-selinux-tests.md
  .github/ISSUE_TEMPLATE/release-upgrade-tests.md
Labels: Hacktoberfest-accepted

#15107 Create release-register-tests.md template to manage register tests
  .github/ISSUE_TEMPLATE/release-register-tests.md
Labels: Hacktoberfest-accepted

#15109 Create release-service-tests.md template to manage service tests
  .github/ISSUE_TEMPLATE/release-service-tests.md
Labels: Hacktoberfest-accepted

#15111 Create release-specific-systems.md template to manage specific systems
  .github/ISSUE_TEMPLATE/release-specific-systems.md
Labels: Hacktoberfest-accepted

#15117 Added bunch of templates of CICD team release
  .github/ISSUE_TEMPLATE/cicd-post-release.md
  .github/ISSUE_TEMPLATE/cicd-release-footprint-metrics.md
  .github/ISSUE_TEMPLATE/cicd-release-installation-metrics.md
  .github/ISSUE_TEMPLATE/cicd-release-packages-tests.md
  .github/ISSUE_TEMPLATE/cicd-release-register-tests.md
  .github/ISSUE_TEMPLATE/cicd-release-selinux-tests.md
  .github/ISSUE_TEMPLATE/cicd-release-service-tests.md
  .github/ISSUE_TEMPLATE/cicd-release-specific-systems.md
  .github/ISSUE_TEMPLATE/cicd-release-stack-tests.md
  .github/ISSUE_TEMPLATE/cicd-release-upgrade-tests.md
  .github/ISSUE_TEMPLATE/footprint_metrics.md
Labels: Hacktoberfest-accepted

#14726 Wazuh agent build on alpine linux
  install.sh
  src/Makefile
  src/error_messages/error_messages.h
  src/headers/log_builder.h
  src/headers/rwlock_op.h
  src/headers/shared.h
  src/init/adduser.sh
  src/logcollector/logcollector.c
  src/remoted/sendmsg.c
  src/rootcheck/os_string.c
  src/shared/log_builder.c
  src/shared/rwlock_op.c
  src/unit_tests/remoted/CMakeLists.txt
  src/unit_tests/remoted/test_sendmsg.c
  src/unit_tests/shared/CMakeLists.txt
  src/unit_tests/shared/test_rwlock_op.c
  src/unit_tests/wrappers/wazuh/shared/rwlock_op_wrappers.c
  src/unit_tests/wrappers/wazuh/shared/rwlock_op_wrappers.h
Labels: module/building, type/enhancement/feature

#13579 Update 0580-win-security_rules.xml rules
  ruleset/rules/0580-win-security_rules.xml
Labels: feed/rules, team/threatintel

#14848 Two integrations don't work at the same time
  src/os_integrator/integrator.c
  src/unit_tests/os_integrator/CMakeLists.txt
  src/unit_tests/os_integrator/test_integrator.c
  src/unit_tests/server.cmake
  src/unit_tests/wrappers/wazuh/shared/json_queue_wrappers.c
  src/unit_tests/wrappers/wazuh/shared/json_queue_wrappers.h
Labels: module/integration

#13594 Adding support for new sysmon events
  ruleset/rules/0595-win-sysmon_rules.xml
  ruleset/testing/tests/sysmon.ini
Labels: feed/rules, team/threatintel

#13608 Add a software limit to limit the amount of EPS that a manager can process
  api/api/api_exception.py
  api/api/configuration.py
  api/api/configuration/api.yaml
  api/api/test/test_configuration.py
  api/api/test/test_validator.py
  api/api/validator.py
  api/scripts/wazuh-apid.py
  api/test/integration/test_agent_GET_endpoints.tavern.yaml
  api/test/integration/test_cluster_endpoints.tavern.yaml
  api/test/integration/test_manager_endpoints.tavern.yaml
  framework/wazuh/core/exception.py
  framework/wazuh/core/tests/test_utils.py
  framework/wazuh/core/utils.py
  src/analysisd/analysisd.c
  src/analysisd/analysisd.h
  src/analysisd/config.c
  src/analysisd/config.h
  src/analysisd/limits.c
  src/analysisd/limits.h
  src/config/config.c
  src/config/config.h
  src/config/global-config.c
  src/config/global-config.h
  src/os_auth/auth.c
  src/unit_tests/analysisd/CMakeLists.txt
  src/unit_tests/analysisd/test_limits.c
Labels: type/enhancement, module/analysis, module/configuration

#14816 Update deprecated value of `KillMode` option in systemd service
  src/init/templates/wazuh-agent.service
  src/init/templates/wazuh-manager.service
Labels: module/upgrade/wpk, module/agent, module/service, platform/linux

#15186 Fix compilation on GCC 4.2.3 for HP-UX
  src/headers/shared.h
  src/os_crypto/shared/msgs.c
Labels: type/bug, module/agent, module/building, platform/hp-ux

#14476 Improve C++ UT coverage
  src/shared_modules/dbsync/src/sqlite/sqlite_wrapper.cpp
  src/shared_modules/dbsync/tests/sqlite/sqlite_test.cpp
  src/shared_modules/utils/tests/stringHelper_test.cpp
Labels: type/test/unit

#14822 Modify OS name's source for macOS
  src/data_provider/src/osinfo/sysOsParsers.cpp
  src/data_provider/src/osinfo/sysOsParsers.h
  src/data_provider/src/sysInfoMac.cpp
  src/data_provider/tests/sysInfo/sysInfoParsers_test.cpp
  src/shared/version_op.c
  src/unit_tests/shared/test_version_op.c
Labels: type/bug, module/agent, module/shared, platform/macos, module/data provider

#11613 OpenWRT decoder fixed and UFW decoder improved
  ruleset/decoders/0140-kernel_decoders.xml
  ruleset/testing/tests/iptables.ini
Labels: type/enhancement, feed/decoders, team/threatintel

#14998 Fixed partial scan for insertion of new packages where triaged is NULL
  src/wazuh_db/wdb.c
Labels: type/bug, module/vulnerability detector, module/syscollector

#14807 Bug fix in wazuh-api-fields decoder
  ruleset/decoders/0007-wazuh-api_decoders.xml
Labels: team/threatintel

#15151 Obtaining the 'aarch64' architecture in the manager and thus fixing the WPK upgrade.
  src/shared/remoted_op.c
Labels: module/upgrade/wpk, platform/amazon linux

#15190 Fix analysisd segfault fired by regex capture group
  src/shared/expression.c
  src/shared/validate_op.c
  src/unit_tests/shared/test_validate_op.c
Labels: type/bug, module/analysis, impact/critical, type/bug/crash

#15253 Add on-demand scan query to Vulnerability Detector
  src/unit_tests/wazuh_modules/CMakeLists.txt
  src/unit_tests/wazuh_modules/vulnerability_detector/CMakeLists.txt
  src/unit_tests/wazuh_modules/vulnerability_detector/test_wm_vuln_detector_run_now.c
  src/unit_tests/wazuh_modules/wmodules/CMakeLists.txt
  src/unit_tests/wazuh_modules/wmodules/test_wmodules.c
  src/wazuh_modules/agent_upgrade/wm_agent_upgrade.c
  src/wazuh_modules/task_manager/wm_task_manager.c
  src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
  src/wazuh_modules/vulnerability_detector/wm_vuln_detector.h
  src/wazuh_modules/wm_aws.c
  src/wazuh_modules/wm_azure.c
  src/wazuh_modules/wm_ciscat.c
  src/wazuh_modules/wm_command.c
  src/wazuh_modules/wm_control.c
  src/wazuh_modules/wm_database.c
  src/wazuh_modules/wm_docker.c
  src/wazuh_modules/wm_download.c
  src/wazuh_modules/wm_fluent.c
  src/wazuh_modules/wm_gcp.c
  src/wazuh_modules/wm_github.c
  src/wazuh_modules/wm_office365.c
  src/wazuh_modules/wm_oscap.c
  src/wazuh_modules/wm_osquery_monitor.c
  src/wazuh_modules/wm_sca.c
  src/wazuh_modules/wm_syscollector.c
  src/wazuh_modules/wmcom.c
  src/wazuh_modules/wmodules.c
  src/wazuh_modules/wmodules.h
  src/wazuh_modules/wmodules_def.h
Labels: type/enhancement, module/vulnerability detector, reporter/operations, type/enhancement/feature
