Repository wazuh/wazuh, pull requests merged in 2023-10, with the labels that each got.

#19144 Add read interface for retrieving Vulnerability Remediation data
  src/wazuh_modules/vulnerability_scanner/CMakeLists.txt
  src/wazuh_modules/vulnerability_scanner/schemas/vulnerabilityCandidate.fbs
  src/wazuh_modules/vulnerability_scanner/schemas/vulnerabilityRemediations.fbs
  src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/databaseFeedManager.hpp
  src/wazuh_modules/vulnerability_scanner/tests/databaseFeedManager/CMakeLists.txt
  src/wazuh_modules/vulnerability_scanner/tests/databaseFeedManager/databaseFeedManager_test.cpp
Labels: type/enhancement, level/task

#19410 Introduce a mechanism to retry the deletion of the database.
  src/shared_modules/dbsync/src/sqlite/sqlite_dbengine.cpp
Labels: type/bug, module/syscollector, level/task

#19595 Fix to generate the CPE for Windows systems without the os_release field
  src/unit_tests/wazuh_modules/vulnerability_detector/test_wm_vuln_detector.c
  src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
  src/wazuh_modules/vulnerability_detector/wm_vuln_detector.h
Labels: type/bug, module/vulnerability detector, platform/windows

#19628 Bump version to 4.9.0
  CHANGELOG.md
  api/api/spec/spec.yaml
  api/setup.py
  framework/setup.py
  framework/wazuh/__init__.py
  framework/wazuh/core/cluster/__init__.py
  src/Doxyfile
  src/REVISION
  src/VERSION
  src/headers/defs.h
  src/init/wazuh-client.sh
  src/init/wazuh-local.sh
  src/init/wazuh-server.sh
  src/win32/version.rc
  src/win32/wazuh-installer.nsi
  src/win32/wazuh-installer.wxs
Labels: request/operational

#19706 Fix to generate the CPE for Windows systems without the os_release field (backport)
  src/unit_tests/wazuh_modules/vulnerability_detector/test_wm_vuln_detector.c
  src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
  src/wazuh_modules/vulnerability_detector/wm_vuln_detector.h
Labels: type/bug, module/vulnerability detector, platform/windows, level/task

#19705 Logcollector module memory leaks in Windows agents
  src/logcollector/logcollector.c
Labels: type/bug, module/logcollector, platform/windows

#19737 Update changelog and revision for 4.5.4
  CHANGELOG.md
  api/api/spec/spec.yaml
  framework/wazuh/core/cluster/__init__.py
  src/Doxyfile
  src/REVISION
  src/init/wazuh-client.sh
  src/init/wazuh-local.sh
  src/init/wazuh-server.sh
  src/win32/wazuh-installer.nsi
Labels: type/change

#19812 Update revision to 40603
  api/api/spec/spec.yaml
  framework/wazuh/core/cluster/__init__.py
  src/Doxyfile
  src/REVISION
  src/init/wazuh-client.sh
  src/init/wazuh-local.sh
  src/init/wazuh-server.sh
  src/win32/wazuh-installer.nsi
Labels: type/change

#19707 Implement read package translations from database
  src/shared_modules/utils/cacheLRU.hpp
  src/shared_modules/utils/tests/CMakeLists.txt
  src/shared_modules/utils/tests/cacheLRU_test.cpp
  src/shared_modules/utils/tests/cacheLRU_test.h
  src/wazuh_modules/vulnerability_scanner/CMakeLists.txt
  src/wazuh_modules/vulnerability_scanner/schemas/vulnerabilityTranslationPackages.fbs
  src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/databaseFeedManager.hpp
  src/wazuh_modules/vulnerability_scanner/tests/databaseFeedManager/databaseFeedManager_test.cpp
Labels: type/enhancement, level/task

#19872 Remove old vulnerability detector configuration
  etc/templates/config/generic/wodle-indexer.manager.template
  etc/templates/config/generic/wodle-vulnerability-detection.manager.template
  etc/templates/config/generic/wodle-vulnerability-detector.manager.template
  src/init/inst-functions.sh
Labels: type/enhancement, level/subtask

#19869 multiarch field default value changed to NULL
  src/data_provider/src/packages/appxWindowsWrapper.h
  src/data_provider/src/packages/brewWrapper.h
  src/data_provider/src/packages/macportsWrapper.h
  src/data_provider/src/packages/packageLinuxApkParserHelper.h
  src/data_provider/src/packages/packagesNPM.hpp
  src/data_provider/src/packages/packagesPYPI.hpp
  src/data_provider/src/packages/solarisWrapper.h
Labels: module/data provider

#19754 Solve rule description update
  ruleset/rules/0520-vulnerability-detector_rules.xml
Labels: type/enhancement, module/vulnerability detector, level/task

#19753 Add agent template excluding /boot for syscheck
  etc/templates/config/aix/syscheck.agent.template
Labels: type/bug, module/fim, platform/aix, level/task

#17306 Enable alert forwarding for Analysisd for all version
  src/analysisd/analysisd.c
  src/analysisd/config.c
  src/config/config.c
  src/config/config.h
  src/config/global-config.c
  src/config/global-config.h
  src/config/localfile-config.c
  src/config/localfile-config.h
  src/config/socket-config.c
  src/headers/mq_op.h
  src/headers/shared.h
  src/logcollector/config.c
  src/logcollector/logcollector.c
  src/logcollector/logcollector.h
  src/logcollector/main.c
  src/shared/mq_op.c
  src/unit_tests/fluentd_forwarder/CMakeLists.txt
  src/unit_tests/fluentd_forwarder/test_fluentd_forwarder.c
  src/win32/win_utils.c
Labels: type/enhancement, module/analysis, module/fluent forwarder, level/task

#19849 Implement default policy configuration values
  src/wazuh_modules/vulnerability_scanner/src/policyManager/policyManager.hpp
  src/wazuh_modules/vulnerability_scanner/tests/policyManager/policyManager_test.cpp
  src/wazuh_modules/vulnerability_scanner/testtool/scanner/config.json
Labels: type/enhancement, level/subtask

#19794 Fix key longer than 65 characters fails in HMAC
  src/os_crypto/hmac/hmac.c
Labels: type/bug

#19889 RockDB Create folders recursively
  src/shared_modules/utils/rocksDBQueue.hpp
  src/shared_modules/utils/rocksDBWrapper.hpp
  src/shared_modules/utils/tests/rocksDBSafeQueue_test.cpp
  src/shared_modules/utils/tests/rocksDBWrapper_test.cpp
Labels: type/enhancement, level/subtask
