Repository wazuh/wazuh, pull requests merged in 2023-11, with the labels that each got.

#19970 Fix compilation error in ubuntu 20.04
  .github/workflows/vulnerability-scanner-tests.yml
  src/shared_modules/content_manager/CMakeLists.txt
  src/shared_modules/content_manager/tests/component/CMakeLists.txt
  src/shared_modules/content_manager/tests/unit/CMakeLists.txt
  src/shared_modules/content_manager/testtool/CMakeLists.txt
  src/shared_modules/indexer_connector/CMakeLists.txt
  src/shared_modules/indexer_connector/tests/unit/CMakeLists.txt
  src/shared_modules/router/CMakeLists.txt
  src/shared_modules/router/tests/component/CMakeLists.txt
  src/shared_modules/router/tests/unit/CMakeLists.txt
  src/wazuh_modules/vulnerability_scanner/CMakeLists.txt
  src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/CMakeLists.txt
  src/wazuh_modules/vulnerability_scanner/tests/databaseFeedManager/CMakeLists.txt
  src/wazuh_modules/vulnerability_scanner/tests/policyManager/CMakeLists.txt
Labels: type/enhancement, level/subtask

#19981 Fix _sys_programs table field constraint
  api/api/spec/spec.yaml
  src/wazuh_db/schema_agents.sql
  src/wazuh_db/schema_upgrade_v13.sql
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_upgrade.c
Labels: type/bug, level/task

#20135 Fix error in SCA Policy For Windows 11 Enterprise
  ruleset/sca/windows/cis_win11_enterprise.yml
Labels: type/bug, type/enhancement, feed/sca, level/task

#20081 Prevent WPK rollback from rebooting the host on Windows agent
  src/win32/do_upgrade.ps1
Labels: module/upgrade/wpk, module/upgrade, platform/windows

#20144 Fix test_encrypt_by_method_aes fails on master
  src/unit_tests/os_crypto/shared/test_msgs.c
Labels: type/bug, type/test, level/task

#20213 Merge 4.7.0 into 4.7.1
  CHANGELOG.md
  api/api/controllers/vulnerability_controller.py
  api/api/spec/spec.yaml
  src/analysisd/analysisd.c
  src/analysisd/analysisd.h
  src/analysisd/limits.c
  src/analysisd/limits.h
  src/analysisd/state.c
  src/client-agent/agentd.c
  src/client-agent/agentd.h
  src/client-agent/buffer.c
  src/client-agent/config.c
  src/config/buffer-config.c
  src/config/client-config.h
  src/headers/limits_op.h
  src/headers/shared.h
  src/shared/limits_op.c
  src/unit_tests/analysisd/CMakeLists.txt
  src/unit_tests/analysisd/test_limits.c
  src/unit_tests/client-agent/test_start_agent.c
  src/unit_tests/shared/CMakeLists.txt
  src/unit_tests/shared/test_limits.c
  src/unit_tests/wrappers/wazuh/analysisd/limits_wrappers.c
  src/unit_tests/wrappers/wazuh/analysisd/limits_wrappers.h
  src/win32/do_upgrade.ps1
  src/win32/win_utils.c
Labels: type/maintenance

#20214 Update changelog for 4.8.0
  CHANGELOG.md
Labels: type/change

#20225 Merge 4.7.1 into 4.8.0
  CHANGELOG.md
  api/api/controllers/vulnerability_controller.py
  api/api/spec/spec.yaml
  api/test/integration/test_rootcheck_endpoints.tavern.yaml
  framework/wazuh/core/tests/test_utils.py
  framework/wazuh/core/utils.py
  integrations/shuffle.py
  integrations/tests/test_shuffle.py
  src/analysisd/analysisd.c
  src/analysisd/analysisd.h
  src/analysisd/limits.c
  src/analysisd/limits.h
  src/analysisd/state.c
  src/client-agent/agentd.c
  src/client-agent/agentd.h
  src/client-agent/buffer.c
  src/client-agent/config.c
  src/config/buffer-config.c
  src/config/client-config.h
  src/headers/limits_op.h
  src/headers/shared.h
  src/shared/limits_op.c
  src/unit_tests/analysisd/CMakeLists.txt
  src/unit_tests/analysisd/test_limits.c
  src/unit_tests/client-agent/test_start_agent.c
  src/unit_tests/shared/CMakeLists.txt
  src/unit_tests/shared/test_limits.c
  src/unit_tests/wrappers/wazuh/analysisd/limits_wrappers.c
  src/unit_tests/wrappers/wazuh/analysisd/limits_wrappers.h
  src/win32/do_upgrade.ps1
  src/win32/win_utils.c
Labels: type/maintenance

#20228 Update changelog for 4.9.0
  CHANGELOG.md
Labels: type/change

#20250 Fix Syscollector decoded data validation at wazuh-analysisd
  src/analysisd/decoders/syscollector.c
Labels: type/bug

#20177 vulnerability scanner module dump function fixed
  src/wazuh_modules/wm_vulnerability_scanner.c
Labels: type/bug, level/task

#20367 Let the manager reject agents with higher versions by default
  src/config/authd-config.h
  src/config/remote-config.h
  src/unit_tests/os_auth/test_authd-config.c
  src/unit_tests/remoted/test_remote-config.c
Labels: module/remote, type/change

#20385 Update changelog for 4.7.0 and bump revision
  CHANGELOG.md
  api/api/spec/spec.yaml
  framework/wazuh/core/cluster/__init__.py
  src/Doxyfile
  src/REVISION
  src/init/wazuh-client.sh
  src/init/wazuh-local.sh
  src/init/wazuh-server.sh
  src/win32/wazuh-installer.nsi
  tools/bump_version.sh
Labels: type/change

#20386 Fix Vulnerability Detection for Windows 11 21H2
  src/unit_tests/wazuh_modules/vulnerability_detector/test_wm_vuln_detector.c
  src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
Labels: module/vulnerability detector, platform/windows

#20415 Merge 4.7.0 into 4.7.1
  CHANGELOG.md
  src/client-agent/start_agent.c
  src/config/authd-config.h
  src/config/remote-config.h
  src/error_messages/error_messages.h
  src/unit_tests/os_auth/test_authd-config.c
  src/unit_tests/remoted/test_remote-config.c
  tools/bump_version.sh
Labels: type/maintenance

#20397 DatabaseFeedManager graceful shutdown improved
  src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/databaseFeedManager.hpp
  src/wazuh_modules/vulnerability_scanner/tests/databaseFeedManager/CMakeLists.txt
  src/wazuh_modules/vulnerability_scanner/tests/databaseFeedManager/databaseFeedManager_test.cpp
Labels: type/enhancement, level/task

#20481 Define a security contribution policy
  SECURITY.md
Labels: type/change

#20495 Merge 4.8.1 into master
  CHANGELOG.md
  framework/setup.py
  src/win32/wazuh-installer.nsi
Labels: type/maintenance

#20514 Merge 4.8.1 into master
  CHANGELOG.md
  etc/templates/config/darwin/23/localfile-extra.template
  etc/templates/config/darwin/23/sca.files
  etc/templates/config/generic/sca.manager.files
  extensions/filebeat/7.x/wazuh-module/README.md
  framework/requirements.txt
  framework/wazuh/core/cluster/cluster.py
  framework/wazuh/core/cluster/common.py
  framework/wazuh/core/cluster/dapi/dapi.py
  framework/wazuh/core/cluster/master.py
  framework/wazuh/core/cluster/tests/test_cluster.py
  framework/wazuh/core/cluster/tests/test_common.py
  framework/wazuh/core/cluster/tests/test_master.py
  framework/wazuh/core/cluster/tests/test_utils.py
  framework/wazuh/core/cluster/tests/test_worker.py
  framework/wazuh/core/cluster/utils.py
  framework/wazuh/core/cluster/worker.py
  ruleset/sca/darwin/23/cis_apple_macOS_14.0.yml
  src/analysisd/decoders/syscheck.c
  src/analysisd/decoders/syscollector.c
  src/client-agent/start_agent.c
  src/config/authd-config.h
  src/config/remote-config.h
  src/data_provider/src/ports/portBSDWrapper.h
  src/error_messages/error_messages.h
  src/init/wazuh/wazuh.sh
  src/unit_tests/analysisd/test_analysisd_syscheck.c
  src/unit_tests/os_auth/test_authd-config.c
  src/unit_tests/remoted/test_remote-config.c
  src/unit_tests/wazuh_db/CMakeLists.txt
  src/unit_tests/wazuh_db/test_wazuh_db_state.c
  src/unit_tests/wazuh_db/test_wdb.c
  src/unit_tests/wazuh_db/test_wdb_global_parser.c
  src/unit_tests/wazuh_modules/vulnerability_detector/test_wm_vuln_detector.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_state_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_state_wrappers.h
  src/wazuh_db/main.c
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_parser.c
  src/wazuh_db/wdb_state.c
  src/wazuh_db/wdb_state.h
  src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c
  tools/bump_version.sh
  wodles/aws/aws_s3.py
Labels: type/maintenance

#20508 Set CURL_DEP variable to avoid libcurl.so dependency on libsysinfo.so
  src/data_provider/CMakeLists.txt
Labels: type/bug, level/task
