Repository wazuh/wazuh, pull requests merged in 2024-09, with the labels that each got.

#25551 Add FIM and Remoted integration tests T2
  .github/workflows/integration-tests-fim-tier-2-lin.yml
  .github/workflows/integration-tests-fim-tier-2-win.yml
  .github/workflows/integration-tests-remoted-tier-2.yml
Labels: type/test

#25544 Add Intune events fields in the Wazuh OpenSearch template
  extensions/elasticsearch/7.x/wazuh-template.json
Labels: type/enhancement, module/msgraph

#25649 Update 4.9.1 release date
  CHANGELOG.md
  packages/debs/SPECS/wazuh-agent/debian/changelog
  packages/debs/SPECS/wazuh-agent/debian/copyright
  packages/debs/SPECS/wazuh-manager/debian/changelog
  packages/debs/SPECS/wazuh-manager/debian/copyright
  packages/rpms/SPECS/wazuh-agent.spec
  packages/rpms/SPECS/wazuh-manager.spec
Labels: type/maintenance

#25588 Restore FIM database data type in Wazuh DB
  src/syscheckd/src/db/src/fimDB.hpp
  src/wazuh_db/schema_agents.sql
Labels: type/bug, module/db

#25952 Fix decoder integration tests and fix a typo
  api/api/spec/spec.yaml
  api/test/integration/test_rbac_black_decoder_endpoints.tavern.yaml
Labels: type/bug, level/task

#25981 Add aarch64 to manager package building workflow
  .github/workflows/packages-build-manager.yml
Labels: type/enhancement, module/install
