Repository wazuh/wazuh, pull requests merged in 2024-02, with the labels that each got.

#21824 Update changelog for 4.8.1
  CHANGELOG.md
Labels: type/maintenance

#21839 Update changelog for 4.8.2
  CHANGELOG.md
Labels: type/maintenance

#21895 Bump version to 5.0.0
  CHANGELOG.md
  api/api/spec/spec.yaml
  api/setup.py
  framework/wazuh/__init__.py
  framework/wazuh/core/cluster/__init__.py
  src/Doxyfile
  src/REVISION
  src/VERSION
  src/headers/defs.h
  src/init/wazuh-client.sh
  src/init/wazuh-local.sh
  src/init/wazuh-server.sh
  src/win32/version.rc
  src/win32/wazuh-installer.nsi
  src/win32/wazuh-installer.wxs
Labels: type/maintenance

#21809 Keystore refactor to enable GTests mockings
  src/shared_modules/indexer_connector/CMakeLists.txt
  src/shared_modules/keystore/CMakeLists.txt
  src/shared_modules/keystore/include/keyStore.hpp
  src/shared_modules/keystore/src/keyStore.cpp
  src/shared_modules/utils/opensslPrimitives.hpp
  src/shared_modules/utils/osPrimitives.hpp
  src/shared_modules/utils/rsaHelper.hpp
  src/shared_modules/utils/tests/CMakeLists.txt
  src/shared_modules/utils/tests/rsaHelper_test.cpp
  src/shared_modules/utils/tests/rsaHelper_test.hpp
Labels: type/enhancement, level/task

#21932 Remove depecrated linker option on macOS 13 Ventura
  src/Makefile
Labels: type/bug, level/task

#22005 Bump revision to 40713
  api/api/spec/spec.yaml
  framework/wazuh/core/cluster/__init__.py
  src/Doxyfile
  src/REVISION
  src/init/wazuh-client.sh
  src/init/wazuh-local.sh
  src/init/wazuh-server.sh
  src/win32/wazuh-installer.nsi
Labels: type/change

#21446 Correcting Vulnerability Detection in Registered Agents
  src/shared_modules/utils/rocksDBWrapper.hpp
  src/shared_modules/utils/socketDBWrapper.hpp
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/cleanUpData.hpp
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/factoryOrchestrator.hpp
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/fetchAllAgentsFromGlobalDb.hpp
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/osDataCache.hpp
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/queryAllPackages.hpp
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanContext.hpp
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanOrchestrator.hpp
  src/wazuh_modules/vulnerability_scanner/src/vulnerabilityScannerFacade.cpp
  src/wazuh_modules/vulnerability_scanner/src/vulnerabilityScannerFacade.hpp
  src/wazuh_modules/vulnerability_scanner/tests/mocks/MockCleanUpData.hpp
  src/wazuh_modules/vulnerability_scanner/tests/mocks/MockFetchAllGlobalDb.hpp
  src/wazuh_modules/vulnerability_scanner/tests/mocks/MockQueryAllPkgsAgt.hpp
  src/wazuh_modules/vulnerability_scanner/tests/mocks/TrampolineFactoryOrchestrator.hpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/detailsAugmentation_test.cpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/factoryOrchestrator_test.cpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/inventorySync_test.cpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/osDataCache_test.hpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/packageScanner_test.cpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/resultIndexer_test.cpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/scanContext_test.cpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/scanOrchestrator_test.cpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/sendReport_test.cpp
  src/wazuh_modules/vulnerability_scanner/testtool/scanner/TC-004/README.md
  src/wazuh_modules/vulnerability_scanner/testtool/scanner/TC-004/step_0.json
  src/wazuh_modules/vulnerability_scanner/testtool/scanner/TC-005/README.md
  src/wazuh_modules/vulnerability_scanner/testtool/scanner/TC-005/step_0.json
  src/wazuh_modules/vulnerability_scanner/testtool/scanner/TC-005/step_1.json
  src/wazuh_modules/vulnerability_scanner/testtool/scanner/argsParser.hpp
  src/wazuh_modules/vulnerability_scanner/testtool/scanner/fakeAgentData/agentOsData.json
  src/wazuh_modules/vulnerability_scanner/testtool/scanner/fakeAgentData/agentPkgsData.json
  src/wazuh_modules/vulnerability_scanner/testtool/scanner/fakeGlobalData/globalData.json
  src/wazuh_modules/vulnerability_scanner/testtool/scanner/main.cpp
Labels: type/bug, level/task

#18680 Remove deprecated plain text auth from AWS and Azure wodles
  src/config/wmodules-aws.c
  src/config/wmodules-azure.c
  src/wazuh_modules/wm_aws.c
  src/wazuh_modules/wm_aws.h
  src/wazuh_modules/wm_azure.c
  src/wazuh_modules/wm_azure.h
  wodles/aws/aws_s3.py
  wodles/aws/aws_tools.py
  wodles/aws/buckets_s3/aws_bucket.py
  wodles/aws/buckets_s3/vpcflow.py
  wodles/aws/services/aws_service.py
  wodles/aws/services/cloudwatchlogs.py
  wodles/aws/services/inspector.py
  wodles/aws/subscribers/s3_log_handler.py
  wodles/aws/subscribers/sqs_queue.py
  wodles/aws/tests/aws_utils.py
  wodles/aws/tests/test_aws_bucket.py
  wodles/aws/tests/test_aws_service.py
  wodles/aws/tests/test_s3_log_handler.py
  wodles/aws/tests/test_sqs_queue.py
  wodles/aws/tests/test_vpcflow.py
  wodles/aws/tests/test_wazuh_integration.py
  wodles/aws/wazuh_integration.py
  wodles/azure/azure-logs.py
  wodles/azure/tests/test_azure.py
Labels: type/enhancement

#20425 Let Windows agent delete state file on stop
  src/win32/win_utils.c
Labels: module/agent, platform/windows

#22178 Enhance auditd log recognition by making "node=" optional
  ruleset/decoders/0040-auditd_decoders.xml
  ruleset/testing/tests/auditd.ini
Labels: type/bug, feed/rules
