Repository wazuh/wazuh, pull requests merged in 2024-04, with the labels that each got.

#22699 Update changelog for 4.8.1
  CHANGELOG.md
Labels: type/change

#22741 Merge changelog of versions 4.8.1 and 4.8.2 into 4.9.0
  CHANGELOG.md
Labels: type/maintenance

#22861 Debian packages generation and debug symbols, migration
  packages/debs/SPECS/wazuh-agent/debian/control
  packages/debs/SPECS/wazuh-agent/debian/rules
  packages/debs/SPECS/wazuh-manager/debian/control
  packages/debs/SPECS/wazuh-manager/debian/rules
  packages/debs/utils/helper_function.sh
Labels: type/enhancement, level/task

#22982 Bump version to v4.7.4
  CHANGELOG.md
  api/api/spec/spec.yaml
  api/setup.py
  framework/setup.py
  framework/wazuh/__init__.py
  framework/wazuh/core/cluster/__init__.py
  src/Doxyfile
  src/REVISION
  src/VERSION
  src/headers/defs.h
  src/init/wazuh-client.sh
  src/init/wazuh-local.sh
  src/init/wazuh-server.sh
  src/win32/version.rc
  src/win32/wazuh-installer.nsi
  src/win32/wazuh-installer.wxs
Labels: type/maintenance

#23004 Exclude containerd folders from Rootcheck scan
  etc/templates/config/alpine/rootcheck.agent.template
  etc/templates/config/centos/5/rootcheck.agent.template
  etc/templates/config/centos/5/rootcheck.manager.template
  etc/templates/config/centos/6/rootcheck.agent.template
  etc/templates/config/centos/6/rootcheck.manager.template
  etc/templates/config/centos/7/rootcheck.agent.template
  etc/templates/config/centos/7/rootcheck.manager.template
  etc/templates/config/centos/8/rootcheck.agent.template
  etc/templates/config/centos/8/rootcheck.manager.template
  etc/templates/config/centos/rootcheck.agent.template
  etc/templates/config/centos/rootcheck.manager.template
  etc/templates/config/debian/10/rootcheck.agent.template
  etc/templates/config/debian/10/rootcheck.manager.template
  etc/templates/config/debian/rootcheck.agent.template
  etc/templates/config/debian/rootcheck.manager.template
  etc/templates/config/fedora/rootcheck.agent.template
  etc/templates/config/fedora/rootcheck.manager.template
  etc/templates/config/generic/rootcheck.agent.template
  etc/templates/config/generic/rootcheck.manager.template
  etc/templates/config/rhel/5/rootcheck.agent.template
  etc/templates/config/rhel/5/rootcheck.manager.template
  etc/templates/config/rhel/6/rootcheck.agent.template
  etc/templates/config/rhel/6/rootcheck.manager.template
  etc/templates/config/rhel/7/rootcheck.agent.template
  etc/templates/config/rhel/7/rootcheck.manager.template
  etc/templates/config/rhel/8/rootcheck.agent.template
  etc/templates/config/rhel/8/rootcheck.manager.template
  etc/templates/config/rhel/9/rootcheck.agent.template
  etc/templates/config/rhel/9/rootcheck.manager.template
  etc/templates/config/rhel/rootcheck.agent.template
  etc/templates/config/rhel/rootcheck.manager.template
  etc/templates/config/sles/11/rootcheck.agent.template
  etc/templates/config/sles/11/rootcheck.manager.template
  etc/templates/config/sles/12/rootcheck.agent.template
  etc/templates/config/sles/12/rootcheck.manager.template
  etc/templates/config/sles/15/rootcheck.agent.template
  etc/templates/config/sles/15/rootcheck.manager.template
  etc/templates/config/suse/11/rootcheck.agent.template
  etc/templates/config/suse/11/rootcheck.manager.template
  etc/templates/config/suse/12/rootcheck.agent.template
  etc/templates/config/suse/12/rootcheck.manager.template
  etc/templates/config/suse/15/rootcheck.agent.template
  etc/templates/config/suse/15/rootcheck.manager.template
  etc/templates/config/ubuntu/rootcheck.agent.template
  etc/templates/config/ubuntu/rootcheck.manager.template
Labels: type/bug, module/rootcheck

#22995 Update changelog for 4.7.4
  CHANGELOG.md
Labels: type/maintenance

#23081 Bump revision to 40716
  api/api/spec/spec.yaml
  framework/wazuh/core/cluster/__init__.py
  src/Doxyfile
  src/REVISION
  src/init/wazuh-client.sh
  src/init/wazuh-local.sh
  src/init/wazuh-server.sh
  src/win32/wazuh-installer.nsi
Labels: type/maintenance

#23130 Bump revision to 40717
  api/api/spec/spec.yaml
  framework/wazuh/core/cluster/__init__.py
  src/Doxyfile
  src/REVISION
  src/init/wazuh-client.sh
  src/init/wazuh-local.sh
  src/init/wazuh-server.sh
  src/win32/wazuh-installer.nsi
Labels: type/maintenance

#23178 Downgrade macOS image version for scan-build test
  .github/workflows/scan-build.yml
Labels: type/bug

#23190 Merge 4.7.4 into 4.8.0
  CHANGELOG.md
  framework/wazuh/core/cluster/client.py
  framework/wazuh/core/cluster/tests/test_client.py
  src/unit_tests/wazuh_db/test_wdb_upgrade.c
  src/wazuh_db/schema_global.sql
  src/wazuh_db/schema_global_upgrade_v6.sql
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_upgrade.c
Labels: type/maintenance
