Repository wazuh/wazuh, pull requests merged in 2024-01, with the labels that each got.

#16284 Remove group and group_hash columns from agent table
  api/api/spec/spec.yaml
  api/test/integration/test_agent_GET_endpoints.tavern.yaml
  framework/wazuh/agent.py
  framework/wazuh/core/agent.py
  framework/wazuh/core/tests/data/test_agent/schema_global_test.sql
  framework/wazuh/core/tests/data/test_database/schema_global_test.sql
  framework/wazuh/core/tests/test_agent.py
  framework/wazuh/core/tests/test_utils.py
  framework/wazuh/tests/data/schema_global_test.sql
  framework/wazuh/tests/test_agent.py
  src/os_auth/main-server.c
  src/remoted/manager.c
  src/unit_tests/os_crypto/md5_sha1_sha256/test_md5_sha1_sha256_op.c
  src/unit_tests/remoted/CMakeLists.txt
  src/unit_tests/remoted/test_manager.c
  src/unit_tests/wazuh_db/CMakeLists.txt
  src/unit_tests/wazuh_db/test_wazuh_db_state.c
  src/unit_tests/wazuh_db/test_wdb_global.c
  src/unit_tests/wazuh_db/test_wdb_global_helpers.c
  src/unit_tests/wazuh_db/test_wdb_global_parser.c
  src/unit_tests/wazuh_db/test_wdb_upgrade.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_helpers_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_helpers_wrappers.h
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_global_wrappers.h
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_state_wrappers.c
  src/unit_tests/wrappers/wazuh/wazuh_db/wdb_state_wrappers.h
  src/wazuh_db/helpers/wdb_global_helpers.c
  src/wazuh_db/helpers/wdb_global_helpers.h
  src/wazuh_db/schema_global.sql
  src/wazuh_db/schema_global_upgrade_v6.sql
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_global.c
  src/wazuh_db/wdb_parser.c
  src/wazuh_db/wdb_state.c
  src/wazuh_db/wdb_state.h
  src/wazuh_db/wdb_upgrade.c
  src/wazuh_modules/wm_database.c
  tests/integration/conftest.py
Labels: type/enhancement, module/db

#21188 Bump version to 4.8.2
  CHANGELOG.md
  api/api/spec/spec.yaml
  api/setup.py
  framework/setup.py
  framework/wazuh/__init__.py
  framework/wazuh/core/cluster/__init__.py
  src/Doxyfile
  src/REVISION
  src/VERSION
  src/headers/defs.h
  src/init/wazuh-client.sh
  src/init/wazuh-local.sh
  src/init/wazuh-server.sh
  src/win32/version.rc
  src/win32/wazuh-installer.nsi
  src/win32/wazuh-installer.wxs
Labels: type/maintenance

#21179 Include cluster_name in vulnerability-detection config
  src/headers/cluster_utils.h
  src/shared/cluster_utils.c
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/detailsAugmentation.hpp
  src/wazuh_modules/wm_vulnerability_scanner.c
Labels: type/bug, level/task

#21208 Bump revision to 40711
  CHANGELOG.md
  api/api/spec/spec.yaml
  framework/wazuh/core/cluster/__init__.py
  src/Doxyfile
  src/REVISION
  src/init/wazuh-client.sh
  src/init/wazuh-local.sh
  src/init/wazuh-server.sh
  src/win32/wazuh-installer.nsi
Labels: type/maintenance

#21219 Update changelog for 4.8.0
  CHANGELOG.md
Labels: type/maintenance

#21220 Merge 4.8.0 into 4.8.1
  CHANGELOG.md
  extensions/filebeat/7.x/wazuh-module/alerts/ingest/pipeline.json
  extensions/filebeat/7.x/wazuh-module/archives/ingest/pipeline.json
  framework/requirements.txt
  src/config/wmodules-vuln-detector.c
  src/wazuh_modules/wmodules.h
Labels: type/maintenance

#21281 Revert "Revert WAF geolocation"
  CHANGELOG.md
  extensions/filebeat/7.x/wazuh-module/alerts/ingest/pipeline.json
  extensions/filebeat/7.x/wazuh-module/archives/ingest/pipeline.json
Labels: type/bug/non production

#21283 Merge 4.8.0 into 4.8.1
  CHANGELOG.md
  extensions/filebeat/7.x/wazuh-module/alerts/ingest/pipeline.json
  extensions/filebeat/7.x/wazuh-module/archives/ingest/pipeline.json
Labels: type/bug/non production

#21289 Update changelog for master
  CHANGELOG.md
Labels: type/maintenance

#21301 Bump revision and update changelog for 4.8.0
  CHANGELOG.md
  api/api/spec/spec.yaml
  framework/wazuh/core/cluster/__init__.py
  src/Doxyfile
  src/REVISION
  src/init/wazuh-client.sh
  src/init/wazuh-local.sh
  src/init/wazuh-server.sh
  src/win32/wazuh-installer.nsi
Labels: type/change

#21338 Introducing std::unordered_map for Matching Package Formats to Corresponding `VersionObjectType`
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/packageScanner.hpp
Labels: type/enhancement, level/task

#21337 UTs added to ResultIndexer class
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/resultIndexer.hpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/resultIndexer_test.cpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/resultIndexer_test.hpp
Labels: type/enhancement, level/subtask

#21331 InventorySync and OsDataCache tests coverage improved
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/inventorySync.hpp
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/osDataCache.hpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/inventorySync_test.cpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/inventorySync_test.hpp
Labels: type/enhancement, level/subtask

#21406 UTs added for class ScanOrchestrator
  src/shared_modules/utils/loggerHelper.h
  src/shared_modules/utils/mocks/chainOfResponsabilityMock.h
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanOrchestrator.cpp
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanOrchestrator.hpp
  src/wazuh_modules/vulnerability_scanner/tests/mocks/MockFactoryOrchestrator.hpp
  src/wazuh_modules/vulnerability_scanner/tests/mocks/TrampolineFactoryOrchestrator.hpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/scanOrchestrator_test.cpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/scanOrchestrator_test.hpp
Labels: type/enhancement, level/subtask

#21445 Method TDatabaseFeedManager::getCnaName was modified to detect vendor…
  src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/databaseFeedManager.hpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/databaseFeedManager_test.cpp
Labels: type/enhancement, level/subtask

#21418 Add UTs coverage for Publisher class on router module
  src/shared_modules/router/src/publisher.hpp
  src/shared_modules/router/tests/unit/publisher_test.cpp
Labels: type/enhancement, level/subtask

#21425 UTs created for PackageScanner class
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/packageScanner.hpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/packageScanner_test.cpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/packageScanner_test.hpp
Labels: type/enhancement, level/subtask

#21447 Auto-adjustment for Time Values Below 60 Minutes
  src/wazuh_modules/vulnerability_scanner/src/policyManager/policyManager.hpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/policyManager_test.cpp
Labels: type/enhancement, level/task

#21460 Package format added as argument to the getCnaName method to temporary skip pypi format packages
  src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/databaseFeedManager.hpp
  src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/packageScanner.hpp
  src/wazuh_modules/vulnerability_scanner/tests/mocks/MockDatabaseFeedManager.hpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/databaseFeedManager_test.cpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/packageScanner_test.cpp
  src/wazuh_modules/vulnerability_scanner/tests/unit/policyManager_test.cpp
Labels: type/enhancement, level/subtask

#21481 Handle correctly multiple configurations
  src/config/indexer-config.c
  src/config/wmodules-vulnerability-detection.c
  src/unit_tests/CMakeLists.txt
  src/unit_tests/config/test_indexer.c
  src/unit_tests/config_files/test_vulnerability_detection.conf
  src/unit_tests/config_files/test_vulnerability_detection_duplicate_configuration.conf
  src/unit_tests/config_files/test_vulnerability_detection_multiple_configuration.conf
  src/unit_tests/wazuh_modules/vulnerability_detection/test_wm_vulnerability_detection.c
Labels: type/bug, level/task

#18353 Refactor agentd integration tests
  .github/workflows/integration-tests-agentd-tier-0-1-lin.yml
  .github/workflows/integration-tests-agentd-tier-0-1-win.yml
  tests/integration/conftest.py
  tests/integration/test_agentd/conftest.py
  tests/integration/test_agentd/test_agentd_multi_server/__init__.py
  tests/integration/test_agentd/test_agentd_multi_server/conftest.py
  tests/integration/test_agentd/test_agentd_multi_server/data/configuration_templates/wazuh_conf.yaml
  tests/integration/test_agentd/test_agentd_multi_server/data/test_cases/cases_reconnection_protocol.yaml
  tests/integration/test_agentd/test_agentd_multi_server/test_agentd_multi_server.py
  tests/integration/test_agentd/test_agentd_parametrized_reconnections/__init__.py
  tests/integration/test_agentd/test_agentd_parametrized_reconnections/data/configuration_templates/wazuh_conf.yaml
  tests/integration/test_agentd/test_agentd_parametrized_reconnections/data/test_cases/cases_reconnection_protocol.yaml
  tests/integration/test_agentd/test_agentd_parametrized_reconnections/test_agentd_parametrized_reconnections.py
  tests/integration/test_agentd/test_agentd_reconnection/__init__.py
  tests/integration/test_agentd/test_agentd_reconnection/data/configuration_templates/wazuh_conf.yaml
  tests/integration/test_agentd/test_agentd_reconnection/data/test_cases/cases_reconnection_protocol.yaml
  tests/integration/test_agentd/test_agentd_reconnection/test_agentd_connection_retries_pre_enrollment.py
  tests/integration/test_agentd/test_agentd_reconnection/test_agentd_initial_enrollment_retries.py
  tests/integration/test_agentd/test_agentd_reconnection/test_agentd_reconection_enrollment_no_keys.py
  tests/integration/test_agentd/test_agentd_reconnection/test_agentd_reconection_enrollment_no_keys_file.py
  tests/integration/test_agentd/test_agentd_reconnection/test_agentd_reconection_enrollment_with_keys.py
  tests/integration/test_agentd/test_agentd_state/__init__.py
  tests/integration/test_agentd/test_agentd_state/data/configuration_templates/wazuh_conf.yaml
  tests/integration/test_agentd/test_agentd_state/data/test_cases/wazuh_state_config_tests.yaml
  tests/integration/test_agentd/test_agentd_state/test_agentd_state.py
  tests/integration/test_agentd/test_agentd_state_config/__init__.py
  tests/integration/test_agentd/test_agentd_state_config/data/configuration_templates/wazuh_conf.yaml
  tests/integration/test_agentd/test_agentd_state_config/data/test_cases/wazuh_state_config_tests.yaml
  tests/integration/test_agentd/test_agentd_state_config/test_agentd_state_config.py
  tests/integration/test_agentd/utils.py
  tests/integration/test_authd/test_authd_key_request_func.py
Labels: type/enhancement, module/agent, level/subtask

#21602 Replace new log checksum chain message from wazuh-monitord
  src/monitord/sign_log.c
Labels: type/enhancement, module/monitord

#21637 Prevent macOS agent installation to start automatically
  src/init/darwin-init.sh
Labels: type/bug, type/enhancement

#21680 Changes to install files, adding new wazuh-keystore tool
  src/init/inst-functions.sh
Labels: type/enhancement, level/task
