Repository wazuh/wazuh, pull requests merged in 2024-03, with the labels that each got.

#22272 Merge 4.7.3 into 4.8.0
  src/unit_tests/wazuh_db/test_wdb_pool.c
  src/wazuh_db/main.c
  src/wazuh_db/wdb.c
  src/wazuh_db/wdb.h
  src/wazuh_db/wdb_pool.c
  src/wazuh_db/wdb_pool.h
Labels: type/maintenance

#22274 Bump revision to 40805
  api/api/spec/spec.yaml
  framework/wazuh/core/cluster/__init__.py
  src/Doxyfile
  src/REVISION
  src/init/wazuh-client.sh
  src/init/wazuh-local.sh
  src/init/wazuh-server.sh
  src/win32/wazuh-installer.nsi
Labels: type/maintenance

#22369 Wazuh-remoted-segmentation-fault
  src/shared/file_op.c
Labels: type/bug/crash

#18001 IT migration - Reorder the way Windows launch its thread to work similarly to other OS
  .github/workflows/integration-tests-agentd-tier-0-1-win.yml
  .github/workflows/integration-tests-execd-tier-0-1-win.yml
  .github/workflows/integration-tests-github-tier-0-1-win.yml
  .github/workflows/integration-tests-office365-tier-0-1-win.yml
  .github/workflows/integration-tests-sca-tier-0-1-win.yml
  .github/workflows/integration-tests-syscollector-tier-0-1-win.yml
  src/client-agent/agentd.c
  src/client-agent/agentd.h
  src/client-agent/receiver.c
  src/syscheckd/src/syscheck.c
  src/unit_tests/syscheckd/CMakeLists.txt
  src/unit_tests/syscheckd/test_syscheck.c
  src/win32/win_utils.c
  tests/integration/test_sca/test_basic.py
Labels: platform/windows, type/change

#22587 Changed cache API option warning logic.
  api/api/configuration.py
  api/api/test/test_configuration.py
  api/scripts/wazuh-apid.py
Labels: module/api, team/framework
