Repository wazuh/wazuh, pull requests merged in 2025-06, with the labels that each got.

#30042 Fix math lib inclusion on AIX
  src/Makefile
Labels: platform/aix, module/building

#30553 Backport: Fix hidden port detection and improve netstat availability handling
  src/headers/file_op.h
  src/rootcheck/check_rc_ports.c
  src/shared/file_op.c
  src/unit_tests/shared/CMakeLists.txt
  src/unit_tests/shared/test_file_op.c
Labels: type/bug, module/rootcheck

#30594 Update cJSON version in README from 1.7.12 to 1.7.18
  README.md
Labels: type/enhancement
